### ISSUE TITLE
[FEATURE REQUEST] SQLServerDataTable and SQLServerDataColumn implementing equals

### ISSUE THREAD

**Issue by lavinj87** [microsoft/mssql-jdbc#1023]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
Given that `SQLServerDataTable` and `SQLServerDataColumn` are final classes (and this is perfectly fine) they can't be mocked with `Mockito` 1.19.

When writing unit tests that interact with those classes, you can build the expected `SQLServerDatatable` and `SQLServerDataColumn` instances and then compare them with the actual instances via `equals()`

Those classes do not implement the equals method, therefore their comparision is via identifical reference, not equality. 

## Describe the preferred solution
An `equals()` (and therefore a `hashCode()` method for both classes, in order to be able to compare not same instances to be equal

## Describe alternatives you've considered
None

## Additional context
The version of the driver is `7.0.0.jre8`

**Comment by cheenamalhotra** [comment]
@lavinj87 

I created PR #1025 to address this request, and also merged PR #1024 with it to write tests in common class. I will close #1024 as we can go forward with the new PR.

Let me know if the PR resolves your query.

**Comment by ulvii** [comment]
Hi @lavinj87,
We had to revert #1025 because it was changing return type of `getRowData()` from `Object[]` to `List<Object>`. This is a breaking change and requires a major version bump. We will re-introduce `equals()` and `hashCode()` in the next preview release. I am re-opening the issue for now, please let us know if you have any questions.

**Comment by lavinj87** [comment]
hi @ulvii 

I see the change at IOBuffer. Couldn't be implemented mantaining the type as an array so that we all can benefit of this PR without breaking version?

Kind regards

**Comment by ulvii** [comment]
We ran into performance issues when using arrays with `hasCode()`, that's why it was decided to use Lists. That being said, prior to re-introducing `equals()`/`hasCode()` in the next preview release, we will look into alternatives whether the requested functionality can be provided without breaking changes.

**Comment by ulvii** [comment]
Hi @lavinj87 ,

The PR #1146 that reintroduces hashCode()/equals() methods in SQLServerDataTable and SQLServerDataColumn is merged now. Please feel free to reopen the issue if you have questions.
