### ISSUE TITLE
[FEATURE REQUEST] Remove set / add methods from ISQLServerBulkRecord

### ISSUE THREAD

**Issue by jonfreedman** [microsoft/mssql-jdbc#1052]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
The ISQLServerBulkRecord interface is a mixture of specification and implementation details.

## Describe the preferred solution
Remove methods which are not called as part of actual bulk copy process via SQLServerBulkCopy#writeToServer.

## Describe alternatives you've considered
Currently it's necessary to implement methods even if they just throw a UnsupportedOperationException

**Comment by cheenamalhotra** [comment]
Hi @jonfreedman 

These exposed APIs are based on driver's implementation of `SQLServerBulkCSVFileRecord` and `SQLServerBulkBatchInsertRecord`. You are right they are not "required" for Bulk Copy operation.

You may choose to ignore these APIs but since they are already public and there will be customers overriding them in their implementations, we would not go ahead for removal. This would cause breaking change for customers implementing and overriding these APIs.

**Comment by jonfreedman** [comment]
Would you accept a pull request that introduced a parent interface (e.g. ISQLServerBulkData) that didn't have this pointless methods?

**Comment by cheenamalhotra** [comment]
Yes, that should be fine 👍
