### ISSUE TITLE
[QUESTION]Performance parameters

### ISSUE THREAD

**Issue by idaamit** [microsoft/mssql-jdbc#1057]
## Question
I'm looking for improving performance in the aspect of accessing DB.
I have seen there are parameters such as : 
hibernate.default_batch_fetch_size
hibernate.jdbc.fetch_size
hibernate.jdbc.batch_size
hibernate.order_updates
hibernate.order_inserts

Does these parameters has affect on performance when working with mssql-jdbc?

**Comment by rene-ye** [comment]
Hi @idaamit, whether those properties will affect performance depends entirely on what hibernate actually calls internally when those flags are turned on. The mssql-jdbc driver do have some similar properties such as fetch_size/batch_size, but whether these properties will improve/affect performance will vary on a case-by-case basis. Maybe this is a better question for the Hibernate team?

**Comment by ulvii** [comment]
Hi @idaamit,

I will try to explain how `hibernate.jdbc.fetch_size` and `hibernate.jdbc.batch_size` might affect the performance of our driver. The other parameters you mentioned are Hibernate specific and I suggest to get help from Hibernate team instead.

`hibernate.jdbc.fetch_size` calls `Statement.setFetchSize()`. To be able to make use of `fetchSize` property, you must first use [server-side cursors](https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-cursor-types?view=sql-server-2017) when creating a statement, to control the amount of data retrieved from server. Usually, the bigger the fetch size is, the less number of round-trips are made to the server, which also results in a performance improvement. However, you should also consider JVM heap memory, because you might run into memory issues when setting fetch size to a large number. Please see [Caching Result Set Data Sample](https://docs.microsoft.com/en-us/sql/connect/jdbc/caching-result-set-data-sample?view=sql-server-2017) for more details and a sample application.

Similar logic applies to `hibernate.jdbc.batch_size` too. Setting batch size to a bigger number results in fewer round-trips to the server, but it might also generate OutOfMemoryError. I would suggest to try different numbers for `fetchSize`/`batchSize` and decide which one gives the best performance for your system. 

I hope this clarifies things a bit. I am closing the issue for now, but please feel free to re-open it if you have any other questions.
