### ISSUE TITLE
[QUESTION] Are fixes for SonarQube issues welcome?

### ISSUE THREAD

**Issue by dvmarcilio** [microsoft/mssql-jdbc#1076]
Hi,

I noticed on the Coding Guidelines that new code should pass SonarQube rules. I wonder if fixes for already committed code are welcome? If yes, I'm more than willing to contribute. 

Thanks!

**Comment by cheenamalhotra** [comment]
@dvmarcilio 
Please go ahead for creating PRs.

Try to create small alike changes that are easy to review and be very careful as some suggestions might not be acceptable due to the existing design of driver.

Also reviewing might take some time as we will be testing the PRs thoroughly for any regressions that may occur. Good Luck!
