### ISSUE TITLE
[QUESTION]:Can I Connect To SSAS Server By This Driver?

### ISSUE THREAD

**Issue by Invoker-liu** [microsoft/mssql-jdbc#1125]

**Comment by lilgreenbird** [comment]
hi @Invoker-liu 

I think the driver should be able to connect to SSAS but I will have to setup an environment to verify and since we have not done extensive testing we can not guarantee full functionality.  

You can find the list of SQL Servers that the driver officially support in [Microsoft JDBC Driver for SQL Server Support Matrix](https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-2017). We have done extensive testing and verified our driver is fully compatible on all servers on this list.

**Comment by lilgreenbird** [comment]
hi @Invoker-liu 

Upon further investigation, I'm afraid I would have to report that you will not be able to connect to SSAS with the driver. SSAS requires [XMLA](https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models-scripting-language-assl-xmla/developing-with-xmla-in-analysis-services?view=sql-server-2017) for communication which is not compatible with our driver.

**Comment by Invoker-liu** [comment]
> hi @Invoker-liu
> 
> Upon further investigation, I'm afraid I would have to report that you will not be able to connect to SSAS with the driver. SSAS requires [XMLA](https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models-scripting-language-assl-xmla/developing-with-xmla-in-analysis-services?view=sql-server-2017) for communication which is not compatible with our driver.

Thank you for your help, I am really grateful to your test,This will save me a lot of time!I will continue to look for other Jar, good luck, thank you again.
