### ISSUE TITLE
[QUESTION] Make internal model public for SQLServerSpatialDatatype class

### ISSUE THREAD

**Issue by MrAolen** [microsoft/mssql-jdbc#1156]
## Question

I am working on a project where I need to translate a `Geometry` object into another spatial class that implement a standard other than WKT/WKB.

I created a class that inherits from `Geometry` in the same package as the `Geometry` object. and I can access to `figureList` field. But the mssql-jdbc jar is signed, I got an error. Is that possible to retrieve figures information with an another way ?

**Comment by peterbae** [comment]
Hi @MrAolen, I've attached my custom preview driver jars to this comment (Java 8/13 builds) that contain the following public getter methods:

SQLServerSpatialDatatype.getPointList()
SQLServerSpatialDatatype.getFigureList()
SQLServerSpatialDatatype.getShapeList()
SQLServerSpatialDatatype.getSegmentList()

Please let me know if this is what you needed, in which case, I'll go ahead and open a PR.

[github-1156.zip](https://github.com/microsoft/mssql-jdbc/files/3708532/github-1156.zip)

**Comment by MrAolen** [comment]
Hello @peterbae, thanks for the fast answer

Yeah it can be useful but the problem is `Point`, `Figure`, `Shape`and `Segment`class are package private. So I think we can put them in public visibility, right?

**Comment by peterbae** [comment]
Hi @MrAolen, those fields are set once the Geometry object is created, and making them public will make them vulnerable to illegal modification (as is the point with any non-public visibility). I've provided the getters instead of changing the fields' visibility because I don't think the Geometry object should be modified once it's been created.

**Comment by MrAolen** [comment]
Yeah I understand, but when I try to use the getter like this:`Geometry.STGeomFromWKB(bytes).getPointList().get(0).getX()`, I got the following error : `: error: Point.getX() is defined in an inaccessible class or interface`.

**Comment by peterbae** [comment]
Hi @MrAolen, the public getters I've provided will let you see the internal values of the spatial datatypes, but it won't let you retrieve the inner classes (point, segment, etc) programmatically since they're internal classes. I don't think we intend to make these internal parts of spatial datatypes as part of our public API, so if you want to be able to manipulate them yourself, you can fork your own branch of the driver and make changes yourself (make the ArrayLists public, extract the internal classes into another file and make them public, etc).

**Comment by MrAolen** [comment]
HI @peterbae, so I understand weel. If we have a multiPolygon we can retrieve all the defined points but we can't retrieve all the necessary information to rebuild the multipolygon in java? Because if we can get the list of all points, we can't access the `pointOffSet` field of `figure` class.

Can we get this information another way?

**Comment by peterbae** [comment]
>If we have a multiPolygon we can retrieve all the defined points but we can't retrieve all the necessary information to rebuild the multipolygon in java?

Correct, we didn't create separate public classes for internal makings of a spatial datatype, since we thought that the spatial datatypes in the driver were only going to be used against SQL Server. Along with the public API's I've created, if we were to move the internal classes (point, figure, etc) into their own public classes, then you would be able to access them as well. I'll look into if it makes sense to turn them into public classes, and get back to you soon.

**Comment by ulvii** [comment]
Hi @MrAolen ,

Would you describe the use case a bit more?  What are you trying to translate Geometry class into? Can you provide an example/reference? As @peterbae mentioned above, making the internal implementation classes public is not an ideal solution and we are trying to figure out if there is a different approach that can be helpful.

Please also list all the classes/fields/APIs that you need access to and give brief explanation why.

**Comment by MrAolen** [comment]
Hi @ulvii ,

the use will be to have one geometry column in a table where I have to insert some multi polygon value. When I try to retrieve this column, I am not able to retrieve all the points of my geometry type and to rebuild the two polygons I insert in my table.

For this I need to access to the `figures`field and access to the `Field` `pointOffset` property. Because , knowing `xValues`, `yValues`and `zValues`, it's not enought to rebuild multi-polygons.

**Comment by sebasbaumh** [comment]
@ulvii The Geometry class should not be an opaque container, but at least allow read access to the underlying geometry points and properties. As a result a user will be able to read the geometry and process it without turning it into a WKT format, which leaves out the SRID and Z/M-values of the 
 coordinates according to your source code.

**Comment by peterbae** [comment]
Hi @MrAolen, @sebasbaumh, I've created a PR that solves this issue. I've also attached the custom jars to this comment. Let me know if this is works as you expected.

[github-1156.zip](https://github.com/microsoft/mssql-jdbc/files/3763603/github-1156.zip)

**Comment by sebasbaumh** [comment]
@peterbae looks good so far 👍

**Comment by peterbae** [comment]
PR has been merged, closing issue.
