### ISSUE TITLE
[FEATURE REQUEST] Refactor SharedTimer

### ISSUE THREAD

**Issue by quaff** [microsoft/mssql-jdbc#1159]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
Currently `SharedTimer` use `refCount` to keep trace of connections, if all connections closed then shutdown underlying `executor`, the `executor` could be created and destroyed frequently, and `synchronized` should be eliminated as possible.

## Describe the preferred solution
Create a singleton of `SharedTimer`, keep alive `executor` and remove `refCount`. register Driver with [DriverAction](https://docs.oracle.com/javase/8/docs/api/java/sql/DriverAction.html) to shutdown `executor` when `DriverManager` perform `deregister`.

**Comment by ulvii** [comment]
Hi @quaff,
We will investigate and get back to you.

**Comment by quaff** [comment]
Here is my immature improvement for reference https://github.com/quaff/mssql-jdbc/commit/0d0b2e8ca7ab33a48b79ea500c4ce7eeacab3a97

**Comment by peterbae** [comment]
Hi @quaff, thanks for letting us know (with an example, too!). I've taken a look at your code and I think this change means that the client application will have to to manually call `DriverManager.deregisterDriver` to shutdown the executor, since we've removed the mechanism (AtomicInteger) that automatically keeps track of how many references to the SharedTimer are there (even though web servers will probably deregister our driver when shutting down, I think we still prefer not to have to rely on it). I also don't see that the driver is calling `SQLServerDriver.deregister` when connections are closing, so the `executor.shutdown` is not going to get called most of the time with this change.

Please let me know what your thoughts are on this.

**Comment by quaff** [comment]
Normally we run application in some containers such as servlet container or IoC container, container could manage long live resources. I'm think introducing a new jdbc url parameter to activate this new strategy, of course default value is disabled to keep compatibility, @peterbae WDYT?

**Comment by peterbae** [comment]
Hi @quaff,

>if all connections closed then shutdown underlying executor, the executor could be created and destroyed frequently

I think this situation won't happen in most application scenarios as they usually have connection pooling, and the executor won't be created/destroyed frequently if the connections are kept alive in the pool. Introducing a connection property for this to me seems like it wouldn't provide much value to the driver. Below is the link from the original issue that is responsible for creating this SharedTimer, which discusses a similar topic:

https://github.com/microsoft/mssql-jdbc/issues/909#issuecomment-447431608

**Comment by quaff** [comment]
👍you convinced me.
