### ISSUE TITLE
[QUESTION] How to using NTLM

### ISSUE THREAD

**Issue by trieutritam** [microsoft/mssql-jdbc#1172]
## Question

Hi all,

Currently, I have an issue with NTLM, the getConnection always return:
`com.microsoft.sqlserver.jdbc.SQLServerException: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication`

Below is my connection string:
jdbc:sqlserver://sqlserverHost;integratedSecurity=true;authenticationScheme=NTLM;domain=ValidDomain;user=ValidUser;password=ValidPassword

Could someone help me with this?

Environment:
- Example code I've used: https://github.com/microsoft/mssql-jdbc/issues/696#issuecomment-496681161
- mssql-jdbc version: 7.4.1-jre8
- OS: MacOS.
- JDK: openjdk version "1.8.0_202"
- SQL Server: Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64)

_Notes: I am able to connect to SQL Server using JTDS with the above information._

**Comment by ulvii** [comment]
Hi @trieutritam ,
Did you try the suggestions on #696? If not, please go through the comments to see if any of the suggestions is helpful. 
If you are still not able to connect, please post **server and JDBC logs** https://github.com/microsoft/mssql-jdbc/issues/696#issuecomment-501414415.

**Comment by ulvii** [comment]
Hi @trieutritam,
`0xC000006A` means incorrect password, please verify the password.
I can't explain why jTDS connects successfully, but I also highly doubt that there is a driver issue with handling NTLM password. 
Have you tried changing the password/use different domain user to connect?

**Comment by ulvii** [comment]
Hi @trieutritam ,
Any updates on this?

**Comment by Smorgasbordq** [comment]
Hello.  I know this issue is nearly a year old, but on a recent deployment of our software, we noticed a similar issue. NTLMv2 authentication failed using v8.2.1 of the driver, but succeeded with one that used the jTDS approach.  I wish I could offer more details at the moment, but it isn't my system (it's a _client_) and I'm not certain what's allowed to be shared.

Taking a peak at Microsoft's and jTDS's approach to NTLM auth, I do notice a few differences off the bat:

1. generateNtlmNegotiate(), the domain is encoded in unicode, but jTDS does it in UTF-8.  Also, the workstation is provided; jTDS does not send this host info.
2. negotiateFlags.  jTDS does not provide NTLMSSP_NEGOTIATE_TARGET_INFO but does add 0x00200 (negotiate NTLM?) during generateNtlmNegotiate().  Microsoft uses the same flags for generateNtlmAuthenticate(), but jTDS drops NTLMSSP_REQUEST_TARGET  | NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED  | NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED with its flags.
3. generateNtlmAuthenticate(), jTDS does not provide version / MIC information; after flags, the domain/user/lmAnswer/ntAnswer are provided in that order. Microsoft does not provide LM length (blanked with short 0 at first), until after the MIC, where it provides the LM length and response, followed by the domain/user/workstation. (I'm assuming this is because of expected differences in the structures of the payload for each NTLM approach, though)

I'll do my best to get more information and play around with it, but considering it's a legacy system with a 'solution' (to use the driver but with jTDS auth code) I'm not sure if much will be done.

**Comment by ulvii** [comment]
Hi @Smorgasbordq ,
The easiest way to figure out why the authentication is failing is to check [SQL Server logs](https://docs.microsoft.com/en-us/sql/relational-databases/performance/view-the-sql-server-error-log-sql-server-management-studio?view=sql-server-ver15), if you could get that we can take a look and go from there.
