### ISSUE TITLE
SQLServerBulkCSVFileRecord should CSV library to split data

### ISSUE THREAD

**Issue by gauravjhs** [microsoft/mssql-jdbc#1173]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
Currently SQLServerBulkCSVFileRecord uses String split method to get data to insert in columns. CSV are generally not as simple as just splitting them using the separator. It gets frustrating when there is some text which contains separator as part of the value.

## Describe the preferred solution
SQLServerBulkCSVFileRecord should use a proper CSV library to extract data from the csv file.

## Describe alternatives you've considered
Generate CSV's using a unique separator which is not present in data(which at times becomes very difficult when data comes from user)

**Comment by cogman** [comment]
Rather than pulling in a library, I'd prefer it if there was an interface to extract that data.  That way the user can provide whatever library they like to handle the parsing logic.

I say this because I'd rather not bring in a CSV parsing lib in my apps for the DB driver.  It isn't a feature I use and I'd rather not pay for it.

Could be as simple as a new constructor that takes in something that looks like this

 `interface DataExtractor extends Iterable<Object[]>{}`

From there it would be simple to make a new DataExtractor that can open any sort of file (Or io stream, or whatever) CSV or otherwise.

Perhaps, at that point, it makes sense to make a new class (rather than attaching this onto the BulkCSVFileRecord)

**Comment by ulvii** [comment]
Hi @gauravjhs, @cogman, 

Thanks for suggestions. I don't think adding a new library as a dependency will magically solve the mentioned limitation without enforcing a CSV format standard. I am proposing to use something similar to [RFC4180 ](https://tools.ietf.org/html/rfc4180) for input CSV files. According to RFC4180, if a field contains the delimiter or line breaks, the field needs to be enclosed in quotes. This can be implemented in the driver without introducing a dependency. Please let me know what you think.

**Comment by gauravjhs** [comment]
@ulvii 
This is a good idea. It will help in removing some shortcomings in existing version without adding any new library. The only reason for me to suggest a CSV framework was to get close to CSV format standard and driver user will not have to worry about CSV if it follows standard specifications.

**Comment by cogman** [comment]
@ulvii Works for me.

I don't know what the transport protocol is for BulkCSV (is it the same as TVPs?).  I know it comes up in docs occasionally as the fastest way to get data into SQL Server.  If there was a way to do this without having to go through a file first that would be really nice.

However, if it is basically the same thing that is happening for TVPs, then I guess I'll just keep using those.

**Comment by ulvii** [comment]
Added SQLServerBulkCSVFileRecord.setEscapeColumnDelimitersCSV() that will parse CSV files according RFC4180. #1312 merged.
