### ISSUE TITLE
[QUESTION]Unable to connect to SQL driver using NTLM

### ISSUE THREAD

**Issue by windwhisper925** [microsoft/mssql-jdbc#1180]
Hi,

I have an issue regarding windows authentication by NTLM in the following environment.
JDBC driver version: 7.4.1. 
SQL server version: SQL server 2016 SP2-CU10. 
Client operating system: Windows Server 2016
SQL server operating system: Windows Server 2016
JDK version: JDK11.0.2.9 from redHat
connectionString: jdbc:sqlserver://url:1433;databaseName=DB;sendStringParametersAsUnicode=false;integratedSecurity=true;authenticationScheme=NTLM;domain=domain;user=user;password=psw

When I tried to connect to SQL server, I hit the following error which was extracted from Event Viewer in SQL server side.
NTLM Minimum Server Security block:
Calling Process PID: 3360
Calling Process Name: PATH_TO_SQLSERVER\bin\sqlservr.exe
Negotiated Security Flags: 0x2818205
Minimum Security Flags: 0x20080000

It is found that OS, which hosts SQL server, has turned on "Require NTLMv2 session security" for “Network Security: Minimum session security for NTLM SSP based (including secure RPC) servers” in policy path "Computer Configuration\Windows Settings\Local Policies\Security Options".

If the above NTLMv2 session security is turned off, using the same code, I can connect to SQL server successfully.
I found that in com.microsoft.sqlserver.jdbc.NTLMAuthentication, the negotiateFlags does not contain 0x80000 (which is the flag for NTLMv2 session security). 
My question is: is there any way for the SQL server JDBC driver 7.4.1 to connect to SQL server successfully with SQL server side OS turning on the "Require NTLMv2 session security" as mentioned above? If it cannot, can this feature be added to a future release of the JDBC driver?

**Comment by ulvii** [comment]
Hi @windwhisper925,

`0x80000` is an NTLMv1 flag, the driver only supports NTLMv2 due to NTLMv1 being insecure. The flag impacts NTLMv2 computations (hence you are seeing a failure), but because it does not add any value to NTLMv2 authentication, we decided to not make use of it. Please update the server to send/accept NTLMv2 requests.

**Comment by windwhisper925** [comment]
Hi @ulvii,

Thank you for your reply. I will investigate further and let you know.

**Comment by windwhisper925** [comment]
Hi @ulvii,

My application is connecting to SQL server using NTLMv2. The above issue encountered is with the following security configurations on SQL Server OS side. Those security configurations are never changed.
![SecuritySettings](https://user-images.githubusercontent.com/40520776/68559523-4fd27280-0478-11ea-8b16-3870965e9d1a.png)

I further read on the flag 0x80000 and found that it is used to "Negotiate NTLM2 Key" for signing and sealing and is used for NTLM2 session security as in http://davenport.sourceforge.net/ntlm.html#appendixC10. This flag seems to be not specific to NTLMv1.

I also tried to do small code change to NTLMAuthentication.java in the jdbc driver as following:
        // NTLM negotiate flags - only NTLMV2 supported
        context.negotiateFlags = NTLMSSP_NEGOTIATE_OEM_WORKSTATION_SUPPLIED | NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED
                | NTLMSSP_REQUEST_TARGET | NTLMSSP_NEGOTIATE_TARGET_INFO | NTLMSSP_NEGOTIATE_UNICODE
                | NTLMSSP_NEGOTIATE_ALWAYS_SIGN | NTLMSSP_NEGOTIATE_EXTENDED_SECURITY_SESSION | **_0x00080000_**;
With this change, my application can connect to SQL server successfully with the above security configurations.

I found a similar issue as in https://github.com/Azure/go-ntlmssp/commit/4a21cbd618b459155f8b8ee7f4491cd54f5efa77#diff-77f3ee43b76ab6843a3f6405e1b8a0c7, which is the same as what I have encountered. Their solution is to add in the flag 0x80000.
Could you please advise on this? 

Thank you for your help.

**Comment by ulvii** [comment]
Hi @windwhisper925 ,

> I further read on the flag 0x80000 and found that it is used to "Negotiate NTLM2 Key" for signing and sealing and is used for NTLM2 session security as in http://davenport.sourceforge.net/ntlm.html#appendixC10. This flag seems to be not specific to NTLMv1.

From the same article: _Negotiate NTLM2 Key Indicates that the NTLM2 signing and sealing scheme should be used for protecting authenticated communications. Note that this refers to a particular session security scheme, and is not related to the use of NTLMv2 authentication. This flag can, however, have an effect on the response calculations._

From [Microsoft NTLM specs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/b38c36ed-2804-4868-a9ff-8dd3182128e4):

_If set, requests usage of the NTLM v2 session security. NTLM v2 session security is a
misnomer because it is not NTLM v2. It is NTLM v1 using the extended session security that is also
in NTLM v2._

Although this is an NTLMv1 flag, I still created #1184  that negotiates NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY flag, because it impacts NTLMv2 calculations.

**Comment by windwhisper925** [comment]
Hi @ulvii,

Thanks for explanation and the changes to the driver. I will close this question.

**Comment by FireInWinter** [comment]
I just ran into the same issue.  So I'm very glad this was found.  Hopefully a new driver won't be too long in the future. @windwhisper925 Thanks for posting the local security settings screen shot.  It helped verify I was seeing the same thing.
