### ISSUE TITLE
ISQLServerBulkRecord methods should not throw SQLServerException

### ISSUE THREAD

**Issue by kesavkolla** [microsoft/mssql-jdbc#1185]
Currently some of methods in ISQLServerBulkRecord has a throws clause with SQLServerException.  This is a problem if any one has to implement a custom BulkRecord implementation.  The SQLServerException class has no public constructor so can't instantiate from the implementation class.

## Describe the preferred solution
The ISQLServerBulkRecord methods should have throws clause with java.sql.SQLException

**Comment by ulvii** [comment]
Hi @kesavkolla ,
Which methods in ISQLServerBulkRecord are you having issues with?

**Comment by kesavkolla** [comment]
All the functions are throwing the SQLServerException.  For ex: getRowData, next etc...
Ideally these should throw java.sql.SQLException.

**Comment by ulvii** [comment]
As of 7.5.0 version of the driver, we deprecated ISQLServerBulkRecord and recommend using ISQLServerBulkData, because ISQLServerBulkRecord was a mix of implementation and specification. You can find more details [here](https://github.com/microsoft/mssql-jdbc/issues/1052). I can apply the changes you requested to ISQLServerBulkData, please let me know if it works for you.

**Comment by kesavkolla** [comment]
Yes please the SQLServerException has no public constructor to use from outher implementation packages so the interface should throw SQLException.  Thanks for the pointer ISQLServerBulkData.  It reduced clutter in my code.

**Comment by ulvii** [comment]
Hi @kesavkolla ,
I created #1187 that should resolve your issue.

> FYI there is no public release of 7.5.0 so had to use 8.1.0 preview version

You are right, the change was introduced in 8.1.0 version of the driver.

**Comment by ulvii** [comment]
#1187 merged.
