### ISSUE TITLE
Geometry class cannot handle 3D WKT

### ISSUE THREAD

**Issue by aaime** [microsoft/mssql-jdbc#1228]
## SQL Server version
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.6 LTS) <X64>     

## Client Operating System
Linux Mint 19.2 (SQLServer is running in the official docker images)

## JAVA/JVM version
OpenJDK 1.8.0_232

## Table schema
No table needed.

## Problem description
The JDBC driver (and the routines inside the database too) cannot handle geometries with Z as specified in the [OGC Simple Feature Specitication](http://portal.opengeospatial.org/files/?artifact_id=25355), see "7.2.3 BNF Productions for Three-Dimension Geometry WKT"
1. Expected behaviour: the code (and the database should parse a valid 3D WKT expression
2. Actual behaviour: it does not, claims Z is invalid
3. Error message/stack trace:

```
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Carattere non valido in Well-Known text alla posizione 12.
	at com.microsoft.sqlserver.jdbc.SQLServerSpatialDatatype.throwIllegalWKTPosition(SQLServerSpatialDatatype.java:1835)
	at com.microsoft.sqlserver.jdbc.SQLServerSpatialDatatype.checkEmptyKeyword(SQLServerSpatialDatatype.java:1489)
	at com.microsoft.sqlserver.jdbc.SQLServerSpatialDatatype.parseWKTForSerialization(SQLServerSpatialDatatype.java:380)
	at com.microsoft.sqlserver.jdbc.Geometry.<init>(Geometry.java:39)
	at com.microsoft.sqlserver.jdbc.Geometry.parse(Geometry.java:128)
	at org.geotools.data.sqlserver.GeometryZTest.main(GeometryZTest.java:9)
```

4. Any other details that can be helpful: Code to reproduce:

```
import com.microsoft.sqlserver.jdbc.Geometry;
import com.microsoft.sqlserver.jdbc.SQLServerException;

public class GeometryZTest {

    public static void main(String[] args) throws SQLServerException {
        Geometry geometry = Geometry.parse("LINESTRING Z(0 0 0, 1 1 1)");
    }
}
```

As an addition, the same problem seems to happen with WKB, the code (and the database routines) cannot parse a valid 3D geometry encoding. To generate such encodings I'd suggest to use the Java Topology Suite WKTWriter and WKBWriter classes.

**Comment by peterbae** [comment]
Hi @aaime, thanks for reporting this. I just looked through the OGC Simple Feature Specification you provided. I agree that as of now, neither SQL Server nor our driver supports the "Z" notation. However, I think SQL Server supports this functionality without the user having to specify the "Z" after the geometry/geography type, since Z (elevation) value can be specified simply by providing the value. 

Either way, since the SQL Server doesn't support this syntax, there's nothing the driver can do as the driver is supposed to mirror the database's functionality. If SQL Server were to add support for this syntax in the future, then the driver will look to add that functionality as well. Please let me know if you have any other questions.

**Comment by aaime** [comment]
@peterbae thanks for the feedback. The standard I referred to is the one that contains the very definition of WKT, its last release dates back to 2011... so getting on par with it would seem like a good idea. Is there a good place where one can open a report against the database itself?

**Comment by peterbae** [comment]
@aaime You can create a new issue or vote on an existing related issue at https://aka.ms/sqlfeedback.

**Comment by peterbae** [comment]
Closing the issue as it's not a driver issue.

**Comment by aaime** [comment]
Reported here: https://feedback.azure.com/forums/908035-sql-server/suggestions/39560161-3d-wkt-support
