### ISSUE TITLE
Why does sendStringParametersAsUnicode default to true?

### ISSUE THREAD

**Issue by beardy247** [microsoft/mssql-jdbc#1367]
Why does sendStringParametersAsUnicode default to true, when with SQLServer2012Dialect String maps to varchar and not nvarchar by default? This has caused me years of performance pain until I discovered this property.

**Comment by rene-ye** [comment]
I believe this is just for backwards compatibility.

**Comment by multicaststorm** [comment]
I feel your pain, I just hit issue because I didn't know about the setting (see #1374)

@rene-ye Surely we don't need this setting if the user uses the correct jdbc api method for getting/setting Unicode strings?
```
setNString(...);
getNString(...);
```

...although I appreciate changing this now could have a backwards compatibility issue.

Maybe a compromise could be to highlight the setting a bit more prominently on the [Improving performance and reliability with the JDBC driver](https://docs.microsoft.com/en-us/sql/connect/jdbc/improving-performance-and-reliability-with-the-jdbc-driver?view=sql-server-ver15) page

**Comment by lukaseder** [comment]
I wonder if this behaviour is really desired, especially if the string doesn't actually contain any unicode data, but just ASCII content, such as `'ABC'`. On the server side, there's an implicit type conversion happening, which prevents indexes on the `VARCHAR` column from being used, see e.g. this report here: https://github.com/jOOQ/jOOQ/issues/11537

We could work around this in jOOQ, by casting all bind values to their actual types, but given that the *default* setting in mssql-jdbc actively prevents any indexes on `VARCHAR` columns from being used by JDBC based applications does seem like a significant bug to me?

**Comment by lukaseder** [comment]
I've analysed this a bit more thoroughly here: https://github.com/microsoft/mssql-jdbc/issues/382#issuecomment-792919818.

**Comment by peterbae** [comment]
@lukaseder thanks for your detailed analysis, and I think the team should revisit this as well. Could you open a new issue with your comment, so that the team can track this better?

**Comment by lukaseder** [comment]
Sure thing, @peterbae, I can do that: https://github.com/microsoft/mssql-jdbc/issues/1538

I just commented on the other issue because @AfsanehR-zz said it could be reopened if there was need: https://github.com/microsoft/mssql-jdbc/issues/382#issuecomment-317550100
