### ISSUE TITLE
[QUESTION] Should I use a static connection?

### ISSUE THREAD

**Issue by Osiris-Team** [microsoft/mssql-jdbc#1405]
## Question
My question is if I should create a new connection to the db, every time a user fetches for data, or only create one final static connection object at the programs start and use it for all the requests.
I think the first approach would be more cpu demanding and the other one more memory demanding.
What do you think?

**Comment by rene-ye** [comment]
Hi Osiris, this question doesn't really have a definite answer and would depend on your use case.

If your use cases are very simple and just send queries to the database, then keeping a single connection alive could very well work just fine. However there are limitations to consider, some of which might be:
- Certain connection properties cannot be toggled off in an active connection
- Certain connection properties cause the connection object to behave differently whether using the property feature or not (AEv2)
- A single connection can only send/receive packets through a single channel. Meaning if you wanted to do multi-threaded work, your multi-threading code will be throttled by the Connection.
- Connections are blocking, meaning if you were to execute a query that takes a long time, you must wait for it to finish before beginning any other queries. This may or may not make sense from the perspective of the application.

That being said, if the use case is very straight forward, there's never a reason to create more connections than necessary. Creating a Connection object for every user query is also quite excessive. Holding Connection objects isn't going to cost much more memory than creating one as you need, so I would choose to keep a Connection object around instead of recreating one if possible.

**Comment by Osiris-Team** [comment]
Thanks for the great answer!
