### ISSUE TITLE
Temporal data types are forced as Varchar for "BulkRecord"

### ISSUE THREAD

**Issue by jackielii** [Microsoft/mssql-jdbc#161]
I tried to implement my own "ISQLServerBulkRecord" based on a "List" type, everything was fine until I discovered I have to convert the Date value to String because of:

[SQLServerBulkCopy.java#L2364](https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L1406)
```java
case java.sql.Types.DATE:
    /*
     * If encrypted, varbinary will be returned before. The code will come here only if unencrypted. For unencrypted bulk copy if the
     * source is CSV, we send the data as varchar and SQL Server will do the conversion. if the source is ResultSet, we send the data as
     * the corresponding temporal type.
     */
    if (null != sourceBulkRecord) {
        return "varchar(" + ((0 == bulkPrecision) ? destPrecision : bulkPrecision) + ")";
    }
    else {
        return "date";
    }
```

Why are we assuming BulkRecord is "CSV" file? I have the date already, I shouldn't need to format it to string and let sql server on the other side to interpret it back to date right?

**Comment by v-suhame** [comment]
@jackielii Thanks for raising this issue. It's a good question, we will fix the issue after analyzing the impact it will have on existing users.

**Comment by jackielii** [comment]
@v-suhame I think the fundamental issue here is:

How can effectively implement my own class that can be accept as input to bulk copy?

**Comment by v-suhame** [comment]
Can you give more detail on what your application is trying to achieve? More specifically, what you are expecting from an `effective implementation`, does it mean less overload on the SQL Server? 

With the driver's current implementation, you can still pass `Date` object to `ISQLServerBulkRecord` and it should work. SQL Server will take care of parsing the value from `Varchar` to `Date`. Even in case of `ResultSet`, the `Date` is still converted to `String` to obtain `Timestamp`.

**Comment by v-suhame** [comment]
Passing smalldatetime via ISQLServerBulkRecord throws `Received an invalid column length from the bcp client for colid 1.`. By default smalldateime doesn't have scale or precision, passing zero as scale and precision throws the exception.

Repro code: 
[ImpISQLServerBulkRecord.txt](https://github.com/Microsoft/mssql-jdbc/files/945432/ImpISQLServerBulkRecord.txt)

**Comment by v-xiangs** [comment]
Hello @jackielii , thank you for the report. 

Both @v-suhame and I have verified the driver works for ISQLServerBulkRecord with `Date` object.

We could implement this without converting `Date` to `String`, however, it will add complexity to the driver. Please let me explain.

The new implementation without conversion would be:
* If `ISQLServerBulkRecord` source is a text file (including CSV), send data values as string (since they are string already in the original source file).
* If `ISQLServerBulkRecord` is not a text file, send data values as they are (e.g. Date object). 
   * However, in this case, we are adding complexity to the driver since the driver needs to check if the source is text file or not. The source can be anything, a file (different extensions), an class or anything else. Also, the driver needs to determine this before sending data, because the driver sends column metadata (TDSType: BIGVARCHAR or DATEN) prior to sending data.

Therefore, always converting to String (Java does the job for us) before sending data value and let SQL Server convert them back to Original type (SQL Server does the job for us) is a safer way to implement this.

**Comment by v-xiangs** [comment]
Hello @jackielii , as we have already verified the `ISQLServerBulkRecord` works with `Date` object and explained the decision to keep the current implementation, is the issue resolved for you now?

**Comment by ajlam** [comment]
Hi @jackielii, we haven't heard from you in a while. Going to close this issue. If you're still running into this issue, please let us know and we can reopen the issue.
