### ISSUE TITLE
Statement property maxRows incorrectly affects count(*) on table valued functions.

### ISSUE THREAD

**Issue by jedvardsson** [Microsoft/mssql-jdbc#176]
Setting statement property ```maxRows``` results in faulty row count on table valued functions.
Below is the output from the supplied test program. The two functions ```numbers_tf```  and ```numbers_itf``` both return 10 rows. The former is table-valued function while the latter is an inlined version instead.

```
maxRows(0): select count(*) from dbo.numbers_itf() => 10  OK!
maxRows(5): select count(*) from dbo.numbers_itf() => 10  OK!
maxRows(0): select count(*) from dbo.numbers_tf() => 10  OK!
maxRows(5): select count(*) from dbo.numbers_tf() => 5  FAILED!
```

As can be seen setting maxRows to 5 changes the count to 5 instead of the expected 10. Clearly this is a bug. MaxRows should only affect the number of rows that the result set returns.

```java
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.ThreadLocalRandom;

public class Main {
    public static void main(String[] args) throws SQLException {
        String url = "jdbc:sqlserver://localhost:1433";
        String user = "sa";
        String password = "Test1234!";
        String database = randomName("test_");
        try (
                Connection c = DriverManager.getConnection(url, user, password);
        ) {
            try {
                executeUpdate(c, "create database " + database);
                executeUpdate(c, "use " + database);


                executeUpdate(c, "create function dbo.numbers_itf()\n" +
                        "returns table\n" +
                        "as return\n" +
                        "    select * from (values (1), (2), (3), (4), (5), (6), (7), (8), (9), (10)) t(num)\n" +
                        "\n");

                executeUpdate(c, "create function dbo.numbers_tf()\n" +
                        "  returns @result table (\n" +
                        "    num int\n" +
                        "  )\n" +
                        "  as\n" +
                        "  begin\n" +
                        "    insert into @result\n" +
                        "    select * from (values (1), (2), (3), (4), (5), (6), (7), (8), (9), (10)) t(num)\n" +
                        "    return\n" +
                        "  end\n" +
                        "\n");


                executeTest(c, 0, "select count(*) from dbo.numbers_itf()", 10);
                executeTest(c, 5, "select count(*) from dbo.numbers_itf()", 10);
                executeTest(c, 0, "select count(*) from dbo.numbers_tf()", 10);
                executeTest(c, 5, "select count(*) from dbo.numbers_tf()", 10);

            } finally {
                executeUpdate(c,"use master");
                executeUpdate(c, "drop database " + database);
            }
        }
    }

    private static int executeUpdate(Connection c, String sql) throws SQLException {
        try (Statement s = c.createStatement()) {
            return s.executeUpdate(sql);
        }
    }

    private static void executeTest(Connection c, int maxRows, String sql, int expected) throws SQLException {
        try (Statement s = c.createStatement()) {
            s.setMaxRows(maxRows);
            s.execute(sql);
            try (ResultSet r = s.getResultSet()) {
                r.next();
                int actual = r.getInt(1);
                System.out.format("maxRows(%d): %s => %d  %s%n", s.getMaxRows(), sql, actual, (actual != expected ? "FAILED!" : "OK!"));
            }
        }
    }

    private static String randomName(String prefix) {
        return prefix + (new BigInteger(40, ThreadLocalRandom.current())).toString(32);
    }

}
```

**Comment by v-afrafi** [comment]
Hi @jedvardsson! This is expected behaviour from sql server. If you run the same queries in sql server you will get the same resutls:

      SET ROWCOUNT 0  
      select count(*) from dbo.numbers_itf()    //returns 10
      select count(*) from dbo.numbers_tf()     //returns 10
      SET ROWCOUNT 5  
      select count(*) from dbo.numbers_itf()   //returns 10
      select count(*) from dbo.numbers_tf()    //returns 5

just to clarify, SET ROWCOUNT applies to any scope for INSERT/UPDATE/DELETE operations and is not effective in inner scopes for SELECT statement (like dbo.numbers_itf()).
 Hope this resolves your issue.

**Comment by gordthompson** [comment]
@v-afrafi - I see some merit in the argument that @jedvardsson is making because

https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#setMaxRows(int)

specifically refers to the maximum number of rows _in a ResultSet object_:

> Sets the limit for the maximum number of rows that any ResultSet object generated by this Statement object can contain

**Comment by v-afrafi** [comment]
@gordthompson  When using setMaxRows(int),  the maxRows will be set to the limit and later when the statement is getting executed, method setMaxRowsAndMaxFieldSize() is called which internally executes "SET ROWCOUNT limit". This will affect the number of rows returned from sql server in ResultSet. 

In this example, in the numbers_itf() function, the INSERT command is affected by the setMaxRow query, therefore server returns only 5 since only 5 is inserted.

**Comment by jedvardsson** [comment]
@v-afrafi I understand the cause of this is ROWCOUNT. However, as @gordthompson points out this goes against the jdbc spec. maxRows is not semantically equivalent to ROWCOUNT.
The current behavior is breaking the JDBC spec.

**Comment by v-afrafi** [comment]
@jedvardsson , @gordthompson Thanks for clarifying this. I understand your point. We will investigate this and update you further. Thanks again.

**Comment by v-afrafi** [comment]
Hi @jedvardsson, according to [JDBC ](https://docs.microsoft.com/en-us/sql/connect/jdbc/reference/setmaxrows-method-sqlserverstatement)specs, in the remarks it also mentions that Microsoft JDBC driver uses set ROWCOUNT and its limitations which we discussed before. While we are investigating this, I suggest using SELECT TOP N in your query as a work around. Thank you.

**Comment by jedvardsson** [comment]
Hi @v-afrafi, Thank you for your your attention to this issue. The link is not to the JDBC spec but to MS JDBC driver implementation of the spec. Anyway, in my case a workaround is not possible. I stumbled across this in IntelliJ Database Console. It seems that the console relies on maxRows in order to paginate the result when executing SQL. Using JTDS driver instead works as expected.

**Comment by v-afrafi** [comment]
@jedvardsson I just tried running your sample code with jtds v1.3.1 and got the same results with our driver. Did you use the same sample code with same jtds version that is working as expected for you?

In the meantime, according to [this](https://msdn.microsoft.com/library/ms188774.aspx), it seems that using SET ROWCOUNT will not be affecting the delete, insert, update statements in future releases of SQL Server. We really appreciate your finding this issue and we will be considering this in our future development work.

**Comment by ajlam** [comment]
@jedvardsson, I think there are two ways we can go about this: 
1) Trying to parse and change the SQL text to use TOP N instead
2) Changing the driver to only return no more than max rows even though the server may have sent more rows

**Comment by TobiasSQL** [comment]
I'd add that #1 has been tried before and failed so it isn't really a feasible robust solution.

**Comment by tonypet** [comment]
Number 2 seems problematic too isn't it? If you run a query from a jdbc app you will get different results than SSMS or other apps.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jedvardsson** [comment]
You're right @v-afrafi, Jtds also uses row count (checked the source code). I must have missed testing Jtds properly.

**Comment by TobiasSQL** [comment]
@tonypet, I am not so sure. Basically the app overrides whatever the server decides to send. To me this is just a setting in the app that modifies the result. We have similar options in SSMS :-) For neither of the below two options it would be OK to return more chars/rows. I would think someone would expect JDBC to adhere to the setting independent on what the server decides to send, in fact, using SET ROWCOUNT is more of an optimization than anything else.

Don't show more than X chars:
![max chars](https://cloud.githubusercontent.com/assets/1648796/24204240/1778c948-0ed5-11e7-8ff9-6def2d351695.png)

Don't show more than Y rows:
![select top](https://cloud.githubusercontent.com/assets/1648796/24204251/1d578db8-0ed5-11e7-8264-1261cce933c8.png)

**Comment by TobiasSQL** [comment]
Sorry, I think we got off topic a bit here (my fault). 

The discussion is if get/setMaxRows should only affect number of returned rows or something else. Where something else is the current behavior... 

Getting back to the spec per @gordthompson, _"Sets the limit for the maximum number of rows that any ResultSet object generated by this Statement object can contain to the given number."_ This seems pretty clear to me. Unfortunately the issue is that changing the current behavior would break apps that rely on it. 

Thoughts?

**Comment by gordthompson** [comment]
I don't think we strayed too far off-topic, given that an important part of the discussion is what the `setMaxRows` property is actually intended to accomplish. Certainly one area where it would be expected to see action is precisely what you described: Limiting the number of rows returned in the default "datasheet view" of a database administration tool like [DBeaver](http://dbeaver.jkiss.org/), as in ...

![dbeaver](https://cloud.githubusercontent.com/assets/15894006/24206843/12cf82f0-0ee5-11e7-802e-643a32144a37.png)

re: "changing the current behavior would break apps that rely on it" - Ay, there's the rub. I suppose one option would be to add a configuration parameter to allow switching back to the old behaviour for those who need it, similar to what MySQL Connector/J did with `useOldAliasMetadataBehavior`.

**Comment by TobiasSQL** [comment]
Changing the behavior and making the new behavior default is pretty dangerous IMHO. To me the sticking point is really that maxRows should be honored in terms of number of rows returned. It seems like we have two "configurations":

1. maxRows explicitly limits number of rows returned (per spec): On/Off
2. Follow maxRows spec completely, i.e. don't use SET ROWCOUN: On/Off

In my mind 1 seems very reasonable and low risk for issues, so I could see that being implemented and on by default.

Overall 2 seems like something not even worth implementing, it could cause serious regressions both in terms of functionality and performance...

Thoughts?

/Tobias

**Comment by gordthompson** [comment]
> Thoughts?

Okay, since you asked ...

> 2. Follow maxRows spec completely
> ...
> Overall 2 seems like something not even worth implementing

"Not even worth [completely] implementing" the JDBC spec in your JDBC driver? 

Ouch.

**Comment by sehrope** [comment]
I can understand maintaining the existing behavior by default in the
interests of backward compatibility, but the current behavior really makes
zero sense for DML.

For queries that return a single result set (i.e. SELECT) it's fine but I
can't imagine any sane situation where a user would want the first N
operations in an INSERT or UPDATE to be performed. Since you're not
specifying the order the operations are being performed (since there is no
explicit order for an insert; it operates on a set), the operation is not
deterministic. Outside of contrived examples, it's ranges from completely
useless, to a foot gun when someone has it globally enabled (say for their
SELECTs) and doesn't fully understand how it works.

Even the docs warn against using it:

> Setting the SET ROWCOUNT option causes most Transact-SQL statements to
stop processing when they have been affected by the specified number of
rows. This includes triggers. The ROWCOUNT option does not affect dynamic
cursors, but it does limit the rowset of keyset and insensitive cursors.
This option should be used with caution.
>SET ROWCOUNT overrides the SELECT statement TOP keyword if the rowcount is
the smaller value.

> The setting of SET ROWCOUNT is set at execute or run time and not at
parse time.


Most importantly, the JDBC spec says that setMaxRowCount(...) is only
supposed to impact ResultSets. I say remove the current behavior, or at
least provide an option for disabling it, and find a different way to limit
the rows returned by a result set that is standards compliant. Earlier in
the thread it's mentioned that future versions will only impact SELECTs,
maybe at that point a version check by the driver can determine whether
it's safe to use.

**Comment by TobiasSQL** [comment]
@gordthompson, now that you put it like that I feel bad... 

I think both yourself and @sehrope agree with the back compat concerns. And I do agree with 1) that it is important to follow the JDBC spec, and 2) that the current behavior is weird and unreliable. And to clear, for any new functionality we should keep aligned with the spec.

The principles we use for SQL Server in terms of changes follow these four steps in priority order (somewhat simplified):
1. Security
2. Don't break existing applications (unless making the software safe demands it)
3. New functionality should be on by default
4. Follow specifications (ANSI SQL standard, JDBC spec, ...), implement new functionality, etc. :-)

Software being safe to use (1) and the fact that an app written once continues working without changes (2) are both key for the long term life of any platform software product. New functionality being on by default is highly desirable otherwise you create complex configuration issues that users have to deal with, this last one is not an absolute though...

I am not saying that we have never broken backwards compatibility, we have. I can for sure say that we regret everyone of those instances unless it was to keep security at the highest of standards.

Now, I may have been a bit quick  (sorry!) to say this is not worth implementing. My worry is that if we cannot break backwards compat the change would have to be off by default which greatly reduces its usefulness. In addition, given this may also have pretty big performance impacts (since the server would not know to create a plan optimized for sending few rows) that reduces the number of times you would actually advice users to turn on the setting. 

There is a proper solution would probably be to support automatically adding TOP/FETCH NEXT to the select statement. This requires very complex logic for a general reliable solution since there may be any number of statements in the string/batch and figuring which ones may be the first result set coming back and injecting the TOP into the syntax is far from trivial. We actually have a similar functionality in SQL Server which is the **sp_describe_first_result_set** spec proc. This proc will return the shape of the first possible result set and it was pretty huge project to implement (think of code branches etc. that have to be handled). 

Finally, like @sehrope mentions maxRows/SET ROWCOUNT/TOP really don't make much sense without ORDER BY in the query. This begs the question why this is even in the JDBC spec (probably for the simple case of preventing too many rows being returned). 

So, it seems to me that the proper solution is to actually modify queries to use TOP/OFFSET/FETCH NEXT + ORDER BY, not to ask the driver. I am not saying we shouldn't do anything but the issue is pretty complex... 

Sorry for the long reply but I felt I didn't convey the right response last time, apologize for that!

Thanks!
-Tobias

**Comment by sehrope** [comment]
> Now, I may have been a bit quick (sorry!) to say this is not worth implementing. My worry is that if we cannot break backwards compat the change would have to be off by default which greatly reduces its usefulness. In addition, given this may also have pretty big performance impacts (since the server would not know to create a plan optimized for sending few rows) that reduces the number of times you would actually advice users to turn on the setting.

I'm fine with breaking backwards compatibility for this since, as mentioned up thread, it really makes no sense to start. I referenced maintaining it out of a general principle of doing so where possible so wouldn't argue against it if that's the consensus.

The primary use case for both setMaxRows(...) and `SET ROWCOUNT` is when executing arbitrary user SQL, generally as either a query editor UI interface or some type of report generation. Both are a crutch to deal with users who don't specify their own TOP/FETCH clauses in the underlying SQL.

In their current state they have no other real world use case and arguably can't be used for this one either as they'd horrible break anyone who could also be doing arbitrary DML. That's why we don't use it. 

Honestly it was very surprising/shocking when we first tried it out and realized that's how `setMaxRows(...)`/`SET ROWCOUNT` ~~works~~ breaks.

> The proper driver solution would probably be to support automatically adding TOP/FETCH NEXT to the select statement. This requires very complex logic for a general reliable solution since there may be any number of statements in the string/batch and figuring which ones may be the first result set coming back and injecting the TOP into the syntax is far from trivial.

-1 from me on this. The driver should not modify the user's SQL.

At best you'll have an unsupportable nightmare that works in a small subset of cases. Dealing with CTEs, RETURNING clauses in DML, and stored procedures that return result sets makes this a non-starter. Plus a SQL command can return multiple result sets and you can't modify the SQL of the innards of a stored procedure.

Having something like this only work for the most basic `SELECT ... FROM ...` would make it pointless.

> We actually have similar functionality in SQL Server which is the sp_describe_first_result_set spec proc. This proc will return the shape of the first possible result set and it was a pretty huge project to implement (think of code branches etc. that have to be handled, it needs to be very efficient etc.).

Having a server side proc to determine the return type for arbitrary SQL isn't bad as the parsing logic is already there. Presumably the server do all the logic for determining what it would do to actually execute the query and then return only the metadata. Having the driver do the same, if done correctly, would require all that same parsing logic and may not even be possible (ex: stored proc calls a different stored proc).

The server also has the blunt approach of actually executing the command in a new transaction, seeing what the result would be, and then rolling it back. I'm sure that has its own issues though.

> Finally, like @sehrope mentions maxRows/SET ROWCOUNT/TOP really don't make much sense without ORDER BY in the query. It can be very useful for UPDATE and DELETE in order to split up a change into multiple batches to make transactions smaller etc. (UPDATE TOP(1000) mytable SET IsChanged = 1, ... WHERE IsChanged = 0) . 

Sure splitting up a large DML into smaller chunks can make sense, but you need a way to track what's being changed (ex: the isChanged flag in your example) and you'd have to run it in a loop too. Having it apply to a WHERE-less `UDPATE foo SET bar = '...'` makes no sense.

> This begs the question why this is in the JDBC spec (probably for the simple case of preventing too many rows being returned as well as supporting databases without much query language).

The setMaxRows() in the JDBC spec only refers to ResultSets and I'm guessing is there in support of the arbitrary SQL use case I described above. It's meant to be a way to provide a hint to the server that you're not going to process the entire result regardless of how it's written so it should try (if possible) to optimize for that.

---

I think what's really needed is a server side change to have `SET ROWCOUNT` (or it's replacement) be a hint to the server that you are only going to fetch the first N rows of whatever result sets are brought back. That way the server doesn't waste CPU/bandwidth on the wire sending the rest of the results (which the driver would need to skip over and discard). Without server side support I don't see a way of this being workable.

**Comment by jedvardsson** [comment]
I second @sehrope. The primary reason for maxRows is executing arbitrary SQL from a tool. This is where I encountered it myself in the first place when using the database console in IntelliJ.

**Comment by TobiasSQL** [comment]
Great conversation! 

> I think what's really needed is a server side change to have SET ROWCOUNT (or it's replacement) be a hint to the server that you are only going to fetch the first N rows of whatever result sets are brought back. That way the server doesn't waste CPU/bandwidth on the wire sending the rest of the results (which the driver would need to skip over and discard). Without server side support I don't see a way of this being workable.

@sehrope I think you are pretty much spot on in terms of the best solution for supporting JDBC  **setMaxRows**: a new server side connection setting with the behavior of only modifying the number of rows returned to the user (not DML, not result of aggregates etc.). Now for me the sticking point is the backwards compat and on/off by default for this new/correct behavior. I do believe strongly in these principles, and at least my perspective is that if we did this it would be off by default. 

From the perspective of adding this to the server I can say that we very rarely add new SET-options for connections because they tend to add complexity and be hard to maintain with correct behavior (SET ROWCOUNT was probably reasonable in behavior at some point...) as well as become feature orthogonality nightmares, i.e. making sure the right options work together the right way and be disallowed when they don't (for ex. combining old SET ROWCOUNT with the new one). They are complex when it comes to dynamic nesting (procedures calling procedures etc.). They also tend to easily introduce bugs in applications since developers may not be aware that they have been set on the connection earlier by for ex. a driver and get unexpected behaviors. I am not saying we never add them but the case has to be really strong. Here I am not sure given the work around of simply using TOP/FETCH NEXT seems to solve the problem for the majority of cases (not the case of a general querying app, on the other hand that particular app type could simply stop fetching when they got enough rows and cancel the query, living with the server side perf impact). It can def. be argued that we made a mistake when first implementing the driver (e.g. we could have thrown an exception on calling setMaxRows instead of doing this implementation)..

Again, we should get the right thing to happen here, just a complex issue :-)

Thanks!
-Tobias

**Comment by jedvardsson** [comment]
The problem here is that maxRows is a property on java.sql.Statement (and all its sub-classes) Therefore, the property is not limited to select statements but should be applied to update-returning statements, procedures (may have multiple result sets) etc.

**Comment by TobiasSQL** [comment]
Correct, any rows being returned to the client independent on why (could come from a trigger). I think definition is clear, implementation harder :)

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by devtomk** [comment]
Calling setMaxRows() on a Statement breaks statements like this: 

```
select *
  into new_table
from some_table;

```
The number of rows inserted into new_table is limited by the value supplied to setMaxRows().

However, calling setMaxRows() on a Statement and then running this insert: 

```
insert into some_table
select *
from other_table;
```
the number of rows will **not** be limited.

**Comment by ulvii** [comment]
Another approach we looked into was to limit the number of rows when reading TDS packets from stream. 
The idea was to count rows in `IOBuffer.readPacket()` - (right after the driver reads the payload of the packet) and discard rest of the packet (also stop reading the next packets from stream) if we reached  `maxRows`. However, we soon realized this would result in double parsing, because the packets are also parsed to generate a `ResultSet`. Hence this approach would be a performance degradation.

**Comment by tseylerd** [comment]
@ulvii Good point. It's the way how it should works (and how other jdbc drivers work). The point about the double parsing seems like an implementation detail. Why not parse it once and use the information to both count rows and create result set?

**Comment by ulvii** [comment]
I did a bit more investigation. Looks like we can count the rows in already consumed packets and discard the remaining rows in those packets after reaching `maxRows`, but problem arises when the server response is returned in multiple packets and we decide not to read the remaining packets. @TobiasSQL , please correct me if I am wrong, if we close the stream when reaching `maxRows` and there are still packets remaining that the driver has not consumed yet, the server would still wait for the driver to process all the packets. So something like the scenario below would fail with the proposed approach. 

```
Statement statement = connection.createStatement();
statement.setMaxRows(10);
//Assume my_table has million rows, hence the server response is returned in multiple packets
//Driver would read first 10 rows, close the stream (ignore remaining packets)
ResultSet rs = statement.executeQuery("select * from my_table");
...
Statement statement1 = connection.createStatement();
//The next line would fail because the driver has not finished processing all the packets from the previous execute
ResultSet rs1 = statement1.executeQuery("select @@Version ");
```
@tseylerd , I checked a few other JDBC drivers, they are able to implement this approach because they are using different protocols, looks like TDS won't let us. 

At this point, we have investigated multiple possible solutions, none of them seem to completely solve the issue with `setMaxRows()`. Please let us know if there are ideas you would like us to look into.

**Comment by ulvii** [comment]
Instead of not reading the remaining packets after reaching `maxRows`, we could try to read and discard  them. This might result in performance degradation when `setMaxRows()` is used, but also make the API JDBC compliant. I am currently looking into this, will try to create a PR as well as a few benchmarks.

**Comment by ulvii** [comment]
Update:
So I tried the approach above - reading and discarding packets after reaching `maxRows`, but this becomes an issue when there are multiple SQL statements in one batch. So we cannot just discard the packets, we need to parse the entire server response to be able to apply the row limit to every result set separately, which would be a huge performance hit. 
Please let us know if you have any ideas regarding the approach I mentioned above,  or any other suggestions to address the issue.

**Comment by ulvii** [comment]
Hi everyone,

Using `SET ROWCOUNT` changes behavior of updates, inserts, deletes, `select count(*)` leading to unexpected/incorrect behavior. We investigated several options to limit the rows from the driver side, but unfortunately all of them are problematic.  

- Adding `TOP` to queries on the client is very complex and error prone. 
- The driver can’t control `TOP` changes when invoking a procedure. 
- The driver can’t use attention because that interrupts secondary activities.
- Reading and discarding TDS packets after reaching `maxRows` is not an option, because there might be multiple result sets. 
- The driver has to stream all rows to acquire output parameters from procedure calls.

Unfortunately, adding a new server side function similar to `SET ROWCOUNT` that would limit the number of rows **only** for result sets does not have the highest priority for SQL Server team, simply because it would be another variation of the existing functionality. 

`SET ROWCOUNT` seems to be the only option for the driver to limit the number of rows at this point.
