### ISSUE TITLE
Create Procedures sp_getTableDDL and sp_getSchemaDDL

### ISSUE THREAD

**Issue by wise-coders** [microsoft/mssql-jdbc#1800]
For automation reasons, I need to have a procedure sp_getTableDDL and sp_getSchemaDDL. Is this possible?
This functionality is available in SSMP, but I would need to access it via the Java JDBC driver. 
This means moving the code to the server and making it available as a procedure.

**Comment by lilgreenbird** [comment]
hi @wise-coders 

We are the Microsoft JDBC Driver for SQL Server team we provide support for the driver only. We do not have any direct contacts to the SQL Server team you will have to go thru Microsoft Support for feature requests for the server.

**Comment by wise-coders** [comment]
Do you know where I can create a ticket for SQL Server team? Maybe you have more rights than me, could you please transfer this ticket to them?

**Comment by lilgreenbird** [comment]
hi @wise-coders 

Unfortunately our team is only responsible for the driver code in this repo. As mentioned we do not have any direct contacts to other product teams. For other MS products you will have to go through MS support. 

Please let us know if you have any driver specific questions otherwise we will be closing this issue shortly.

**Comment by wise-coders** [comment]
Ok, I got it. You can close this ticket.
