### ISSUE TITLE
[QUESTION] JDBC driver version and DB compatibility level

### ISSUE THREAD

**Issue by mattgagliardi** [microsoft/mssql-jdbc#1824]
## Question

How does a given JDBC driver version’s database compatibility (SQL version compatibility listing [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver15) ) map to SQL database compatibility level? For example, if I’m running the 7.2.2 JDBC driver version that table doesn’t show compatibility with SQL 2019. If I deploy a DB into a SQL 2019 instance but set the DB’s compatibility level to 130 (SQL 2016) should I expect the driver to work?

**Comment by tkyc** [comment]
Hi @mattgagliardi, from what I know, it should work since the compatibility levels are used to maintain application backwards compatibility.

Just a fyi, from the driver perspective for the (compatibility listing matrix)[https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver15](url), when it describes a driver as not being compatible with a SQL Server version, it means that we're dropping testing against the particular SQL Server version. Potentially, the driver should work with all SQL Server versions and there's just driver features that won't work.

**Comment by mattgagliardi** [comment]
@tkyc with respect to the idea that the matrix showing incompatibility (no "yes" in the column) I understand that an older version of SQL would imply testing was dropped.  Is the converse also true, that in the case of a newer version of SQL (ex. 7.2.2 driver and SQL 2019) it indicates that the driver was not tested against that version of SQL...it may work but hasn't been confirmed?
Is there somewhere I can see which features have been added to a given driver?  Perhaps that's in the release notes?  Thanks :)

**Comment by tkyc** [comment]
@mattgagliardi Right, correction to what I said earlier, if the matrix shows incompatibility that means testing was not done. So, that means either we dropped testing or didn't test in the first place.

So yes, in your example (v7.2.2 and SQL 2019), it was never tested and so potentially might work. For the release notes, you can find the official ones [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver15). You can also find them on github [here](https://github.com/microsoft/mssql-jdbc/releases) or you can switch to the driver version tag within the project and view them in the changelog (eg. [here's the changelog for v7.2.2](https://github.com/microsoft/mssql-jdbc/blob/v7.2.2/CHANGELOG.md).

**Comment by tkyc** [comment]
Closing, as question is resolved.
