### ISSUE TITLE
[QUESTION] Is DefaultAzureCredential supported

### ISSUE THREAD

**Issue by saragluna** [microsoft/mssql-jdbc#1881]
## Question
By looking at this https://github.com/microsoft/mssql-jdbc#azure-key-vault-and-azure-active-directory-authentication-dependencies, seems like the `azure-identity` is included when talking to Azure
AD. I am wondering whether the [DefaultAzureCredential](https://www.rahulpnath.com/blog/defaultazurecredential-from-azure-sdk/)  is supported.

**Comment by stliu** [comment]
`DefaultAzureCredential` is not supported in the JDBC connection stage I think, actually by looking into the code, seems azure-identity is only used by the KeyVault Client auth.

From the [current code](https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L5425), I think the auth methods supported by the ms SQL jdbc driver are fixed, it is impossible to extend w/o changing the existing code.

I'm thinking to make it extensible, we can do the following change:

1. the [authentication property](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16), we can make it accept one more type of value, which is a class FQDN name.
2. create an new interface, for example `FedAuthTokenResolver`
3. in [this code](https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L5425), at the end of that long **if-else** check, we add one more check to see if `authenticationString` is a class name which is on the classpath and implements the `FedAuthTokenResolver`

**Comment by tkyc** [comment]
That's correct, at the moment the JDBC driver doesn't support `DefaultAzureCredential`.

Since the semester is coming to an end, and is soon to be concluded with a GA release, I'll bring this up with the team in our planning.

Thanks @stliu for the implementation insights.

**Comment by saragluna** [comment]
Hi @tkyc and @lilgreenbird, any updates on this feature request? Will this be included in this semester?

**Comment by tkyc** [comment]
Hey @saragluna, unfortunately this feature request didn't make it in this semester. We'll update you once it's out of the backlog.

**Comment by tkyc** [comment]
Hey all, an upcoming preview with this feature will be released on Nov 3rd.

**Comment by saragluna** [comment]
@tkyc thanks. Could you help point us to the doc where we can follow how to use the new feature?

**Comment by tkyc** [comment]
@saragluna Apologies, official docs aren't available yet.

To use the `DefaultAzureCredential`, you just need to do the following:

- Add the property/value pair `authentication=DefaultAzureCredential` to your connection string

- To use the `ManagedIdentityCredential` in the `DefaultAzureCredential`, additionally provide `user=<your-managed-identity-client-id>` or `msiClientId=<your-managed-identity-client-id>` to your connection string eg. `jdbc:sqlserver://<your-server-name>:1433;database=<your-database-name>;authentication=DefaultAzureCredential;user=<your-managed-identity-client-id>;`

- To use the `IntellijCredential` on windows, set the environment variable `INTELLIJ_KEEPASS_PATH` to the location of your keepass file eg. `INTELLIJ_KEEPASS_PATH=`C:\user\your\path\to\the\keepass\file`

- To provide additional tenants, use the `ADDITIONALLY_ALLOWED_TENANTS` environment variable. This is a comma delimited list eg. `ADDITIONALLY_ALLOWED_TENANTS=<your-tenant-id-0>,<your-tenant-id-1>,<your-tenant-id-2>,....`

Otherwise, if you setup the appropriate configurations mentioned here at the [official Azure Identity](https://learn.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable) for the other credential types under the `DefaultAzureCredential` (eg. Environment, CLI, Powershell credentials), then it should also work.

**Comment by saragluna** [comment]
Hi @tkyc, there are some issues when trying the new authentication method. This approach will narrow the credential provider to a fixed type: the `DefaultAzureCredential`. But as a framework to develop on top of the SQL JDBC driver, it could be possible that we pass in another credential type. Is there a way that we can provide an extensible mechanism to let users provide their authentication? As demoed in this PR https://github.com/microsoft/mssql-jdbc/pull/1884?

**Comment by tkyc** [comment]
Hey @saragluna, sorry to hear about this issue. I'll need to review the current implementation again. I'll let you know afterwards.
