### ISSUE TITLE
[QUESTION] Why multiple release artifacts?

### ISSUE THREAD

**Issue by carlmolemans** [microsoft/mssql-jdbc#1894]
## Question
Why do you have a release for each LTS jre plus latest jre? 
Can't you just release 1 mssql-jdbc jar with a minimum java requirement, eg. 11+ and be done with it? 

If this has already been answered, link me up Scotty.

**Comment by Jeffery-Wasty** [comment]
Hi @carlmolemans,

Because the MSSQL-JDBC driver is used in many different environments, with many different OS and Java versions, we try to extend compatibility and support for the driver to cover as many of these use cases as possible. At some point, however, it becomes unrealistic to continue support for a particular environment that is well out of date. The dates we use for this cutoff, for Java versions, can be found [here](https://www.oracle.com/java/technologies/java-se-support-roadmap.html). So, as of this date, August 10th 2022, we can see that Oracle has extended support for Java 8, 11, 17, and 18, and thus we support all of these versions in our releases.

**Comment by Jeffery-Wasty** [comment]
With the question being answered, I've gone ahead and closed this issue. Feel free to drop a comment if you'd like to discuss this further.

**Comment by Jeffery-Wasty** [comment]
Just an update on this. While the Java 8 version should be retained, it may be possible to consolidate the remaining versions into one, leaving us with just two versions of the driver, as opposed to four. This is something we can re-examine in the future.
