### ISSUE TITLE
UTF-8 encoding for resultset metadata doesn't work from JDBC Driver version greater than 7.2.2 

### ISSUE THREAD

**Issue by impothnis** [microsoft/mssql-jdbc#2057]
## Driver version
Provide the JDBC driver version (e.g. 10.2.0).

Works fine in 6.2.1.jre8 version 
Fails from any driver version greater than 7.2.2.jre8 version 

## SQL Server version
Provide the output of executing `SELECT @@VERSION` on your target SQL Server.

Microsoft Azure SQL Data Warehouse - 10.0.18045.0 Oct 11 2022 03:10:58 Copyright (c) Microsoft Corporation

## Client Operating System
Provide the Operating System the client application is running on.

Windows 10 / Linux RHEL and Ubuntu 

## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").

Java 1.8 

## Table schema
Provide the table schema to repro the issue.

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AzureDW_DIatScale].[tk_日本人_日本人_日本人_日本人_src]
(
	[日本] [nvarchar](100) NULL,
	[日本人] [nvarchar](100) NULL,
	[日本人_日本人] [nvarchar](100) NULL,
	[eng] [varchar](30) NULL,
	[new_col] [varchar](30) NULL,
	[nCol] [varchar](10) NULL,
	[nCol1] [varchar](10) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

## Problem description
Provide full details of the problem.

Create a table with the above schema 

get the colum metadata using Java + JDBC Driver 
ResultSet resultSet = metadata.getColumns( null, "AzureDW_DIatScale", "tk_日本人_日本人_日本人_日本人_src", null );

Print the column names 
 System.out.println((resultSet.getString("COLUMN_NAME"))); 

output from 6.2.1.jre JDBC driver 
日本日本人日本人_日本人engnew_colnColnCol1

output from 11.2.1.jre JDBC driver 
????????_???engnew_colnColnCol1

## Expected behavior
Expected output 

日本日本人日本人_日本人engnew_colnColnCol1

output from 11.2.1.jre JDBC driver 
????????_???engnew_colnColnCol1

## Actual behavior
Output of what you actually see.

output from 11.2.1.jre JDBC driver 
????????_???engnew_colnColnCol1

## Error message/stack trace
Complete error message and stack trace.
No Error message, however the columns name are not encoded properly as it is done till 7.2.2.jre8 JDBC driver
## Any other details that can be helpful
Please note - This is not related to IDE encoding or the machine encoding or the configuration and purely JDBC Driver issue, as it works fine when use JDBC driver version till 7.2.2.jre8 and fails post that. 

## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

		Logger logger = Logger.getLogger("com.microsoft.sqlserver.jdbc.Statement");
		logger.setLevel(Level.FINEST);

Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 setResponseBuffering
FINER: ENTRY adaptive
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 setResponseBuffering
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 executeQuery
FINER: ENTRY SELECT CAST(SERVERPROPERTY('EngineEdition') as INT)
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 executeQuery
FINER: RETURN SQLServerResultSet:1
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 close
FINER: ENTRY
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 close
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setResponseBuffering
FINER: ENTRY adaptive
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setResponseBuffering
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setString
FINER: ENTRY 1 tk_日本人_日本人_日本人_日本人_src
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setString
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setString
FINER: ENTRY 2 AzureDW_DIatScale
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setString
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setString
FINER: ENTRY 3 INFASQLDW_DEV
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setString
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setString
FINER: ENTRY 4 %
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setString
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setInt
FINER: ENTRY 5 2
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setInt
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setInt
FINER: ENTRY 6 3
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 setInt
FINER: RETURN
Jan 27, 2023 8:40:46 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 executeQuery
FINER: ENTRY
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 executeQuery
FINER: RETURN
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:3 setResponseBuffering
FINER: ENTRY adaptive
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:3 setResponseBuffering
FINER: RETURN
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:3 executeQuery
FINER: ENTRY
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:3 executeQuery
FINER: RETURN
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:3 closeOnCompletion
FINER: ENTRY
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:3 closeOnCompletion
FINER: RETURN
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 close
FINER: ENTRY
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:2 close
FINER: RETURN
??
???
???_???
eng
new_col
nCol
nCol1

Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:4 setResponseBuffering
FINER: ENTRY adaptive
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:4 setResponseBuffering
FINER: RETURN
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:4 getMetaData
FINER: ENTRY
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerStatement:5 setResponseBuffering
FINER: ENTRY adaptive
Jan 27, 2023 8:40:47 PM com.microsoft.sqlserver.jdbc.SQLServerStatement:5 setResponseBuffering
FINER: RETURN
Jan 27, 2023 8:40:48 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement:4 getMetaData
FINER: RETURN  SQLServerResultSetMetaData:1
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

**Comment by tkyc** [comment]
I'm unable to repro the issue from your description as I was able to print the characters successfully with drivers post v7.2.2. I don't see how you are getting `???` for the characters if environment encoding isn't the issue. Like your settings, I have mine set to UTF-8 as well.

Could you provide an exact repro app for us?

**Comment by impothnis** [comment]
We have spent considerable amount of time with Synapse tem at Microsoft on the incident 2301240030001337  and they have been able to reproduce this issue in their environment, will it be possible to sync up with them and work it out internally, I will ask MSFT team to reach out and provide the repro.

**Comment by tkyc** [comment]
I'm reviewing the support thread/ticket you mentioned. It looks like v11.2.1 was verified to not be able to view the characters, but I don't see a mention of v6.2.1 being tested to view the characters. I'll need to confirm with them as v6.2.1 had the same behaviour as v11.2.1 for me depending on the environment encoding.

**Comment by lilgreenbird** [comment]
just to clarify, we are seeing the same results on all versions of the driver including 6.2.1 so we are asking if you had tried the same application in the same environment with version 6.2.1 as well as 11.2.1 of the driver? Note in Windows terminal, you need to change locale to UTF-8 in order to see characters such as chinese characters, this has nothing to do with the driver you will need to do that if you had a text file containing characters in chinese encoding as well.

**Comment by tkyc** [comment]
I've reviewed the support ticket. They're saying v6.2.1 wasn't able to successfully view the characters but v6.4.0 can. However, when I tested with their repro on v6.4.0 and v6.2.1, I still wasn't able to view the characters (all this was done on a fresh environment like before). I inclined to say this isn't a driver issue, but I'll standby for more info for the time being unless I'm wrong somewhere.

**Comment by impothnis** [comment]
Please note - This is not related to IDE encoding or the machine encoding or the configuration and purely JDBC Driver issue, as it works fine when use JDBC driver version till 7.2.2.jre8 and fails post that.

This was mentioned in the Any additional details that can help section, while raising the issue. We have observed that it UTF-8 characters works fine till version 7.2.2 and starts to fail from there till the latest version available.

**Comment by tkyc** [comment]
Hi, I've managed to repro the problem with the help of MSFT support engineeers and I've identified the exact cause. I already communicated this to the support engineers on your case, but I'll also leave a summary of my findings on this thread as well.

The reason that the characters aren't visible is because of the meta query to get the column name information. This meta query is selecting against the database and if the database collation doesn't support the characters then the characters will of course not be visible. The meta query is written this way for two reasons. getColumns needs to be JDBC compliant, meaning that the column names of the result set it returns needs to match what is defined in the JDBC spec. For this reason, we need to use table variables to correct the column names to be compliant in the meta query. However, Azure DW does not support table variables nor insertion of data into temp tables from `exec` calls. So, the meta query is written in way that doesn't depend on these sorts of syntax, but doing so affects the character encoding as you have seen. The older driver versions (< 7.2.2) are working because they directly do a transact-sql query for the column info which isn't affected by collation/encoding, but the result set isn't JDBC compliant. So, there isn't an easy way to fix this in the driver. The only immediate solution I see is to switch the collation of the database to a collation that supports the characters. If I learn anything more, I'll let you know.

As for a future fix, it doesn't seem likely with the constraints I mentioned prior. The trade off here is either being JDBC compliant or be affected by encoding. While being affected by encoding isn't ideal, it can be worked around by setting the db to a collation that supports the characters. Whereas not being JDBC compliant can't really be worked around on the user side.
