### ISSUE TITLE
Wrong jdbc type for datetime column 

### ISSUE THREAD

**Issue by tseylerd** [Microsoft/mssql-jdbc#208]
On SQL Server 2005 ResultSetMetadata.getColumnType for DATETIME column returns -151 value wich is not member of java.sql.Types. A think something like Types.TIMESTAMP should be returned.

**Comment by gordthompson** [comment]
I see what you mean. However, version 6.x of the JDBC driver for SQL Server does not support SQL Server 2005. Under "System Requirements" on [this page](https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774) we see ...

> Supported SQL Server Versions:
> • Microsoft SQL Server 2016
> • Microsoft SQL Server 2014
> • Microsoft SQL Server 2012
> • Microsoft SQL Server 2008 R2
> • Microsoft SQL Server 2008
> • Azure SQL Database
> • Azure SQL Data Warehouse or Parallel Data Warehouse

... so I doubt that a fix for SQL Server 2005 will be forthcoming.

**Comment by v-xiangs** [comment]
hello @tseylerd, thank you for filling the issue.
In `src/main/java/microsoft/sql/Types.java`, we define data types that are specific to Microsoft SQL Server. Those data types are not defined in `java.sql.Types`. 

We know this is not a perfect solution, but we have to assign different int values to them in order to distinguish them among other data types. Therefore, we cannot assign `Types.TIMESTAMP` to `DATETIME`, otherwise the driver would fail somewhere, especially with Always Encrypted enabled. Instead, we give a value of -151, which is not used by any `java.sql.Types`. So the driver knows the type of the data and can handle the data base on the type.

**Comment by v-nisidh** [comment]
@tseylerd : We are closing this issue as we did not hear anything from you. Please feel free to reopen this issue with your comments.
