### ISSUE TITLE
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "No negotiable cipher suite".

### ISSUE THREAD

**Issue by leishenglong** [microsoft/mssql-jdbc#2166]
## Driver version

12.2.0.jre8，7.4.1.jre8
## SQL Server version
Provide the output of executing `SELECT @@VERSION` on your target SQL Server.
	Sep 24 2019 13:48:23 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

## Client Operating System
Provide the Operating System the client application is running on.

## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)
## Table schema
Provide the table schema to repro the issue.

## Problem description
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "No negotiable cipher suite". ClientConnectionId:d1b85ebe-1d53-4143-830d-ed5dd453afb3

## Expected behavior
The database connection is  normal 
## Actual behavior
[13:26:48:114] [ERROR] - org.dbsyncer.connector.database.DatabaseConnectorMapper.execute(DatabaseConnectorMapper.java:33) - The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "No negotiable cipher suite". ClientConnectionId:d1b85ebe-1d53-4143-830d-ed5dd453afb3
[13:26:48:114] [ERROR] - org.dbsyncer.parser.ParserFactory.isAliveConnectorConfig(ParserFactory.java:121) - The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "No negotiable cipher suite". ClientConnectionId:d1b85ebe-1d53-4143-830d-ed5dd453afb3
## Error message/stack trace
Complete error message and stack trace.
## Any other details that can be helpful
The window environment is normal, and the Linux is abnormal
## JDBC trace logs
sorry，The database environment is on the customer's side

**Comment by tkyc** [comment]
From what I know when dealing with cipher suites, it's a usually a problem on the JDK side rather than driver side. Here are somethings you can try to narrow down the problem.

1. Use Oracle's JDK 8 (or any other JDK 8 from any other vendor). Different JDKs may have different cipher suites enabled. So if the application does work on some other JDK it is likely this reason.

2. Enable `-Djavax.net.debug=all` and provide the output. It should list the cipher suites willing to be used for negotiation. Compare this list with the cipher suites enabled in the JDK used (disabled/not enabled ciphers are listed in the `jdk.tls.disabledAlgorithms` property in the `java.security` file in the JDK). And, compare this list with the ciphers enabled on the server (you'll need to look up the platform specific cli commands to do this eg. for Windows it's `Get-TlsCipherSuite`, on linux if I recall correctly you can use the `openssl` command).

**Comment by tkyc** [comment]
Hi, it's been awhile and since there's no new info I'm closing this. Feel free to reopen if you have new info.
