### ISSUE TITLE
Feature request - API method to retrieve number of rows returned in ResultSet

### ISSUE THREAD

**Issue by ghost** [Microsoft/mssql-jdbc#219]
It seems that there is no way simple way to get the number of rows in a returned ResultSet without scrolling or additional queries (implicit or @@ROWCOUNT).

**Comment by v-xiangs** [comment]
Hello @avader906 , thank you for the feature request. In order to assist you better, could you please let us know why you want to have an API that retrieves number of rows instead of calling `count(*)`, `@@ROWCOUNT` or `ResultSet.last() and ResultSet.getROW()`?

**Comment by avader906** [comment]
@v-xiangs The reason is that none of your trivial and well documented suggestions work in practice. 

The issue arises when working with TB size tables (partitioned or not) - and where the client needs to pre-allocate resources to handle the query results. May I suggest you verify it yourself on a test table (200mio rows / 65 cols - to give you approx size of our use cases).

1) ResultSet.last/ResultSet.getRow requires unnecessary overhead in terms of cursor other than read-only  (java.sql.ResultSet.TYPE_FORWARD_ONLY, java.sql.ResultSet.CONCUR_READ_ONLY) and has the horrible latency

2) A separate count(*) is unacceptable too. If it was a table - we would of queries the systems tables of row sizes, but this is not available unless we create and index the view beforehand.

3) the @@ROWCOUNT does not work using JDBC - a separate createStatement gets FetchSize window size. 

4) The best procedure we found (other than creating and indexing views beforehand), was to add helper tables with {1,0} query result set membership accordingly, index and then sum (across all partitions). But this is not practical either, even though we save time overall.

We do not know the SQL Server internals nor your JDBC driver API to understand if the query resultset count information is available to consume beforehand and thus can be exposed via JDBC. But without any doubt,, it would be a huge improvement to the driver and the whole stack. BR

**Comment by v-xiangs** [comment]
@avader906 Thank you for your very detailed response. I will definitely verify it myself and keep you updated. Thank you.

**Comment by v-nisidh** [comment]
@avader906: You are talking about a very large amount of data. In the JDBC world, one of the best practices is your solution should not rely on count of rows if you are dealing with huge result set. In case of small result set, you can use count query. 
 
Are you able to provide more details on your scenario or technology stack your application is using? 
 
For simplicity I am considering pagination scenario . If you are using spring / hibernate then you can get pagination in-built. Although if you are not using any ORM tool & your framework is not supporting pagination then you can use **offset, fetch & next** combination.  (Ref: http://stackoverflow.com/questions/21537511/sql-server-query-with-pagination-and-count)
 
To give the count, the driver and server need to process all rows, which is equivalent to having 2 queries count and select. Otherwise, everything would need to be kept in-memory, which is also not practical.  In any large dataset, the most efficient way is stream out results from server & driver need to consume that as it gets it.

**Comment by avader906** [comment]
@v-nisidh thank you for your comment. please read the entire thread next time prior to replying.

Implementation of the requested feature is proper to MSSQL and how it exposes rowcount. If exposed rowcount, *under server side cursor*, reflects the entire resulting query size - then JDBC driver could take advantage of that information and provide it to the user prior to loading the first resultSet page.

**Comment by ajlam** [comment]
Deprioritizing this issue and closing.
