### ISSUE TITLE
Springboot 15.21 cannot be linked to SQL Server 2012, is it a version incompatibility?

### ISSUE THREAD

**Issue by taidilixiang** [microsoft/mssql-jdbc#2270]
**Driver version**
mssql-jdbc-6.1.0.jre7
**SQL Server version**
Microsoft SQL Server 2012

**JAVA/JVM version**
java1.8
com.alibaba.druid 11.10

**Problem description**
Springboot 15.21 cannot connect to sqlserver2012, but can connect to sql2008,
To connect to sqserver2012, it seems necessary to use mssql-jdbc -9.2.1jre11. However, when Spring Boot version 1.5.21 matches mssql-jdbc -9.2.1jre11, it prompts' overlapping managed version 6.1.0.jre7 for mssql-jdbc ', but cannot connect to sqserver2012 using 6.1.0.jre7.
Excuse me, is it possible to connect to sqserver2012 in Spring Boot version 1.5.21 without upgrading to Spring Boot?

If the situation requires upgrading Springboot to connect to sql2012, what is the version of Springboot, Alibaba. druid, and mssql-jdbc iin order to connect to sqlserver2012?

If you can only upgrade to mssql-jdbc to 9.2.1jre11 to connect to SQL Server 2012, then Java cannot use version 1.8. Do Java versions also need to be upgraded?

Requesting everyone's help.

Partial configuration information in application.yml
```
datasource:
 
url: jdbc:sqlserver:/172.16.128.137:1433;databaseName=MQSF
 
password: 1
 
username: sa
 
driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
 
type: com.alibaba.druid.pool.DruidDataSource
```
 
Partial configuration information in pom.xml

```
<parent>
 
<groupId>org.springframework.boot</groupId>
 
<artifactId>spring-boot-starter-parent</artifactId>
 
<version>1.5.21.RELEASE</version>
 
<relativePath/> <!-- lookup parent from repository -->
 
</parent>
 
 
 
<properties>
 
<java.version>1.8</java.version>
 
</properties>
 
 
 
<dependency>
 
<groupId>com.microsoft.sqlserver</groupId>
 
<artifactId>mssql-jdbc</artifactId>
 
<scope>runtime</scope>
 
</dependency>
 
<dependency>

```
**Error message/stack trace**

```
2023-12-01 05:44:24.390 [Druid-ConnectionPool-Create-1412600960] ERROR com.alibaba.druid.pool.DruidDataSource - create connection SQLException, url: jdbc:sqlserver:/172.16.128.137:1433;databaseName=MQSF, errorCode 0, state null

java.sql.SQLException: connect error, url jdbc:sqlserver:/172.16.128.137:1433;databaseName=MQSF, driverClass com.microsoft.sqlserver.jdbc.SQLServerDriver

at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection([DruidAbstractDataSource.java:1627](https://link.zhihu.com/?target=http%3A//druidabstractdatasource.java%3A1627/))

at [com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run](https://link.zhihu.com/?target=http%3A//com.alibaba.druid.pool.druiddatasource%2524createconnectionthread.run/)([DruidDataSource.java:2468](https://link.zhihu.com/?target=http%3A//druiddatasource.java%3A2468/))
```
```[tasklist]
### Tasks
```

**Comment by Jeffery-Wasty** [comment]
Hi @taidilixiang,

I tried to find information on Spring Boot compatibility, but was unable to do so, so I can only speak for the MSSQL-JDBC side of this issue. Both driver version 6.1.0 and 9.2.1 are compatible with SQL Server 2012 as per [our support matrix](https://learn.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver16). To answer your questions:

> However, when Spring Boot version 1.5.21 matches mssql-jdbc -9.2.1jre11, it prompts' overlapping managed version 6.1.0.jre7 for mssql-jdbc '

This is not a driver error, I would suggest reaching out to Spring Boot support on how to resolve this error.

> Excuse me, is it possible to connect to sqserver2012 in Spring Boot version 1.5.21 without upgrading to Spring Boot?

> If the situation requires upgrading Springboot to connect to sql2012, what is the version of Springboot, Alibaba. druid, and mssql-jdbc iin order to connect to sqlserver2012?

Both of these are questions regarding Spring Boot that I was unable to find an answer for. Driver compatibility with SQL Server 2012 is all listed in the link pasted above.

> If you can only upgrade to mssql-jdbc to 9.2.1jre11 to connect to SQL Server 2012, then Java cannot use version 1.8. Do Java versions also need to be upgraded?

Since at least version 6.1.0, Java 8 has been supported for every release.

Finally, I should note, driver versions 7.0 and below are no longer receiving support from the JDBC team (this information is also in the provided link). Our recommendation if you are using a version below 7.2, is to upgrade to a driver version 7.2 or above. The preference is you use the latest stable version. A reminder that all versions from 6.1 and up support Java 8.

**Comment by taidilixiang** [comment]
The connection has been successful, it is a problem with the database server settings. Thank you all for your enthusiastic help.
