### ISSUE TITLE
WARNING Discarding unexpected TDS_COLMETADATA (0x81) printout when calling DatbaseMetadata.supportsTransactions()

### ISSUE THREAD

**Issue by uffeweil** [microsoft/mssql-jdbc#2281]
## Driver version
12.4.2.0

## SQL Server version
Microsoft SQL Server 2022 (RTM-CU10) (KB5031778) - 16.0.4095.4 (X64) 
	Oct 30 2023 16:12:44 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 22.04.3 LTS) <X64>

## Client Operating System
MacOS sonoma 14.2.1 (23C71)

## JAVA/JVM version
- Tested with: java 17.0.9+9 and Java 11.0.18+10 both have the same problem

## Problem description
Getting a **WARNING**: printout when calling DatbaseMetadata.supportsTransactions().

Java program to reproduce the problem is attached. [SqlServerBug.txt](https://github.com/microsoft/mssql-jdbc/files/13739574/SqlServerBug.txt)

(Run with mssql-jdbc-12.4.2.jre11.jar in classpath)
Getting the following output when running.
`Running on Java: 17.0.9+9
Connect successful. Driver:12.4.2.0   Database: 16.00.4095
Calling supportsTransactions ..
Dec 21, 2023 10:13:06 AM com.microsoft.sqlserver.jdbc.TDSTokenHandler onColMetaData
WARNING: ConnectionID:1 ClientConnectionId: d70af3f1-2d10-470a-8cea-89a8accd2549: SQLServerConnection.supportsTransactions: Discarding unexpected TDS_COLMETADATA (0x81)
   Result:true

## Expected behavior
No WARNING

**Comment by uffeweil** [comment]
Forgot to mention that printout also seems to happen at other occasions as well. E.g. calling Statement.setMaxrows

**Comment by Jeffery-Wasty** [comment]
Hi @uffeweil,

This is an expected warning when something that is producing extra metadata is ON.

For the case with `Statement.setMaxrows`, and most other cases, try setting the SHOWPLAN off (i.e. `conn.createStatement().execute("SET SHOWPLAN_ALL OFF");`).

For the case with `supportsTransactions`. It looks like this is triggered by an extra call on our end for `SELECT @@TRANCOUNT`, in order to probe for whether transactions are supported. It's not possible to turn this call without reintroducing the issue it was intended to fix. We'll look into whether this can be handled differently, we don't like having stray warnings, but this will likely be a lower priority issue.

**Comment by uffeweil** [comment]
Hi Jeffery,
Thanks for responding. 

I guess it's safe then for us to ignore this  warning (map it to INFO).
 
Kind regards
Ulf
