### ISSUE TITLE
Does this version run on Android?

### ISSUE THREAD

**Issue by ARMSALIM** [microsoft/mssql-jdbc#2423]

**Comment by David-Engel** [comment]
We don't test on Android and support would be limited. But it's written to be able to generally work on any Java runtime with the exception of some authentication features and Windows certificate store features for Always Encrypted. Give it a try and let us know how it goes.

**Comment by ARMSALIM** [comment]
Dear David

Thank you for your mail.

My android app compiles without any error with the JDBC jar file.

I've even set the sql network connection to use force encryption and
attached a self signed certificate,
but when connecting to the sql server db using connection string:

*"jdbc:sqlserver://server:port;databaseName=xxx;ssl=request;encrypt=true;integratedSecurity=true;trustServerCertificate=true;sslProtocol=TLSv1.2"*


I have the following error:

*com.microsoft.sqlserver.jdbc.SQLServerException: "encrypt" property is set
to "true" and "trustServerCertificate" property is set to "true"*

*but the driver could not establish a secure connection to SQL Server by
using*

*Secure Sockets Layer (SSL) encryption: Error: Socket is closed.
ClientConnectionId:736a1781-3cbf-4c27-9c51-39b1ac07e41a*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:4277)*

* at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1966)*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3803)*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3391)*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:3200)*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1974)*

* at
com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1263)*

* at java.sql.DriverManager.getConnection(DriverManager.java:569)*

* at java.sql.DriverManager.getConnection(DriverManager.java:219)*


Kindly advise.

Regards
Salim

**Comment by David-Engel** [comment]
That's an unusual error. Perhaps due to trying to use integrated security on Android, but not sure. I'm pretty sure Integrated security won't work on Android anyway. Also, `ssl` isn't a valid option for the mssql-jdbc driver (it will be ignored). I'd try SQL authentication to keep things simple for now and ensure there isn't something else wrong. And let the client/server choose the encryption protocol for now:
`jdbc:sqlserver://server:port;databaseName=xxx;encrypt=true;trustServerCertificate=true;username=<sql username>;password=<password>`

**Comment by ARMSALIM** [comment]
Hi David

I've done exactly as per your suggestion and still have the same issue.

Connection string:

*jdbc:sqlserver://server:port;databaseName=???;encrypt=true;trustServerCertificate=true;username=???;password=???*

Error:

*com.microsoft.sqlserver.jdbc.SQLServerException: "encrypt" property is set
to "true" and "trustServerCertificate" property is set to "true" but the
driver could not establish a secure connection to SQL Server by using
Secure Sockets Layer (SSL) encryption: Error: Socket is closed.
ClientConnectionId:42d60a5b-8832-449c-a339-6bd7392bfdba*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:4277)*

* at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1966)*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3803)*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3391)*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:3200)*

* at
com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1974)*

* at
com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1263)*

* at java.sql.DriverManager.getConnection(DriverManager.java:569)*

* at java.sql.DriverManager.getConnection(DriverManager.java:219)*


Even without certificate or force-Encrytion disabled, the Microsoft JDBC
does not work.

However, the  *JDBC JTDS provided by Sourceforge* does work on MS SQL only
when ForceEncrytion is disabled.
But the latter is quite old and has not been updated since 2013.

That is why I wanted to switch to MS JDBC, while hoping to get a better
update.

Will Microsoft do needful for Android OS?

Regards
Salim

**Comment by Jeffery-Wasty** [comment]
Hi @ARMSALIM,

We're not fully clear on the environment the driver is running in on Android OS, but its perfectly possible that the environment is missing key encryption libraries or features that the driver requires. jTDS succeeds in your above case because of the different approach taken to encryption with jTDS. With the jTDS driver, encryption is not always required, whereas with the JDBC driver, it is. Even if you were to set `encrypt` to false with the JDBC driver, it most likely will still fail as encryption is needed for establishing the connection. My recommendation is as follows, either:

- Use the jTDS driver, keeping in mind the encryption restrictions, or
- Find some way to setup the necessary encryption perquisites in Android OS. I'm not clear on what these are, as I am not familiar with how Android OS is set up.

There are no current plans to set up a Android version of the driver.

Please let us know if you have any further questions. If not we will move forward with closing this issue.
