### ISSUE TITLE
Release naming causing issues for revision checking software

### ISSUE THREAD

**Issue by rob-elsevier** [microsoft/mssql-jdbc#2445]
## Driver version
implementation group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '12.6.2.jre11'

With recent released to Maven there are issues with the naming of some of the packages that is causing tools such as https://github.com/ben-manes/gradle-versions-plugin to be unable to validate the latest version to automate picking up the latest bug and security fixes.

More details discussed in the following ticket:

https://github.com/ben-manes/gradle-versions-plugin/issues/869

**Comment by ben-manes** [comment]
This is more serious. The release files being named inconsistently with the version coordinates means the dependency cannot be used by build tools. Gradle fails to resolve and likely others will too.

**Comment by Jeffery-Wasty** [comment]
Thanks, we'll consider other solutions for this besides what I listed on the previous thread, and keep you updated with our decisions.

**Comment by Jeffery-Wasty** [comment]
I've double-checked with the team. We have no way to remove 'bad' releases from Maven. The only solution for this issue is to wait until the [12.8.0 release](https://github.com/microsoft/mssql-jdbc/milestone/78) (which is on July 31st, 2024) and to use that as the stable version in the plugin configuration as opposed to 12.6.2. As well, users will need to refrain from using versions <= 12.7.0 to avoid the same problem. We will update this thread again when 12.8.0 has been released.

**Comment by Jeffery-Wasty** [comment]
12.8.0 has been released, fixing the above issue. Closing issue.
