### ISSUE TITLE
Followup question on https://github.com/microsoft/mssql-jdbc/issues/2463

### ISSUE THREAD

**Issue by HarshaVardhan-Sai** [microsoft/mssql-jdbc#2474]
## Question
@Jeffery-Wasty mentioned that the fix would be in the preview release of 12.7.1. Could you please help us on the expected stable release date?
I do not see the release notes of 12.7.0 on the release notes page but maven repository points me that there is a 12.7.0 release.
At this moment when my functions have the parenthesis I get a default zero output hence i see its related to https://github.com/microsoft/mssql-jdbc/issues/2463.

**Comment by Jeffery-Wasty** [comment]
Hi @HarshaVardhan-Sai,

My comment was as follows:

> Fix has been merged, will be available for 12.7.1 Preview (planned in the next week) and 12.8.0 GA Release (July 31).

The 12.7.1 preview is now available on [GitHub](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.7.1). The release will be available on Maven soon (still needs to be indexed by Maven). As mentioned in the comment, this is a preview release with the stable release planned for the end of this month (July 31).

Additionally, we do respond to conversation on closed issues. Since this is a follow-up to #2463, in the future, please leave a comment on the original thread.
