### ISSUE TITLE
JDBC batch update performance issue

### ISSUE THREAD

**Issue by msenthilnathan-cvlt** [microsoft/mssql-jdbc#2511]
## Driver version
12.8.1.jre11.jar

## SQL Server version
Microsoft SQL Server 2016 (SP2-GDR) (KB4583460) - 13.0.5108.50 (X64) 
	May 20 2022 20:28:29 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: )

## Client Operating System
Windows

## JAVA/JVM version
java SE 20

## Table schema
CREATE TABLE xxx.dbo.Attachment_BlobStatus (Id varchar(18) ,Status varchar(20) );
CREATE NONCLUSTERED INDEX IDX_Id_Attachment_BlobStatus ON dbo.Attachment_ID 

## Problem description
We have around 200k rows in this table. 
Running update statment in the attached sample. Each batch of 2000 recds take 10+ secs.

## Actual behavior
Output of what you actually see.
## Error message/stack trace
Complete error message and stack trace.
![AttachmentBlobStatusUpdateJava](https://github.com/user-attachments/assets/c428cfca-232e-4981-9e77-3ad9cdf54cf7)

## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by tkyc** [comment]
How's the performance when you run a `SET NOCOUNT ON` before your batch calls?

And also, how do older driver versions fair? Could you try 9.4.1, 10.2.3, 11.2.3 and 12.4.2?

**Comment by msenthilnathan-cvlt** [comment]
Can i attach the source file to this email chain? Github does not allow files other than Images etc.

Also, SETcount off did not help either.

Going back to older versions-may be ok for comparison/debugging purposes. But, we doubt we can do it permanently in production.


Thanks

On Sep 11, 2024, at 1:15 PM, Terry Chow ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
External email. Inspect before opening.



Also, can you give me the source code for your issue and any thing else that I might require to recreate the setup on my own environment. Thanks.

**Comment by tkyc** [comment]
@msenthilnathan-cvlt

You should be able to zip it and upload it to your comment.

**Comment by msenthilnathan-cvlt** [comment]
[AttachmentBlobStatusUpdater.zip](https://github.com/user-attachments/files/16981518/AttachmentBlobStatusUpdater.zip)

java source file zipped

**Comment by tkyc** [comment]
@msenthilnathan-cvlt 

In progress of getting this setup...

But, could you try adding `sendStringParametersAsUnicode=false` in your connection string. Let me know if there's a performance difference.

**Comment by msenthilnathan-cvlt** [comment]
Thanks Terry. In my quick test, this seems to had done the trick. Compared to 14 sec response, with this param, response is instantaneous.

Will test some more and incorporate it in our product code and get back.

Can you please share any documentation on this?
Since connection is used for other SQL updates, which may need to send parameters in Unicode - how to use this without such side effects?

Thanks
Senthil

**Comment by tkyc** [comment]
@msenthilnathan-cvlt

Thanks for the quick test. This confirmed my suspicions. It was a perf impact because of an implicit conversion from varchar to nvarchar.

>Can you please share any documentation on this?
Since connection is used for other SQL updates, which may need to send parameters in Unicode - how to use this without such side effects?

For this doc, scroll down to the `sendStringParametersAsUnicode` section:
https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16

https://learn.microsoft.com/en-us/sql/connect/jdbc/reference/setsendstringparametersasunicode-method-sqlserverdatasource?view=sql-server-ver16

As for safely using this, I'd recommend operating solely on exclusively varchar or nvarchar (for example) with your connections and set `sendStringParametersAsUnicode` appropriately beforehand. That'd be the best. We default to unicode to prevent accidental data loss as backwards compatibility, since this was the initial behaviour in the driver.

**Comment by tkyc** [comment]
Just adding a bit more details. The perf impact occurred because your table had a column defined as varchar, but since the driver by default sends parameters to server in unicode, there was an implicit conversion going from varchar to nvarchar. This implicit conversion caused the slowness.

So, migrating your columns eg. varchar, char etc... to nvarchar or nchar etc... and using `sendStringParametersAsUnicode=true` would increase performance also.

**Comment by msenthilnathan-cvlt** [comment]
Yes, but we know the data stored is only English in this case. There are many other tables also - that are to track internal data that don't need to NVARCHAR. Will that not result in overallocation and also slowness in sorting/comparisons?
Seems, setString() and setNString() should be used depending on the data types; but, its probably too big of a change for our product at this change.  Will explore how to do this - may be only for selected updates/queries.

Appreciate the suggestions !!
