### ISSUE TITLE
Analyze JDBC 4.3 proposed changes

### ISSUE THREAD

**Issue by v-nisidh** [Microsoft/mssql-jdbc#268]
**JDBC 4.3 API**
- [x] Check JDK 9 & JDK 8 API changes.
- [x] JDBC 4.3 API . Ref: http://download.java.net/java/jdk9/docs/api/java/sql/package-summary.html

**[java.sql and javax.sql Features Introduced in the JDBC 4.3 API](http://download.java.net/java/jdk9/docs/api/java/sql/package-summary.html)**

1. Added Sharding support (ShardingKey & ShardingKeyBuilder)
1. Enhanced Connection to be able to provide hints to the driver that a request, an independent unit of work, is beginning or ending 
1. Enhanced DatabaseMetaData to determine if Sharding is supported
1. Added the method drivers to DriverManager to return a Stream of the currently loaded and available JDBC drivers
1. Added support to Statement for enquoting literals and simple identifiers
1. Clarified the Java SE version that methods were deprecated

One can see java doc [diff](https://jcp.org/aboutJava/communityprocess/maintenance/jsr221/221ChangeLog.html) & download [proposed changes](https://jcp.org/aboutJava/communityprocess/maintenance/jsr221/JDBC4.3MR-January2017.pdf).

**Links:** 
- [MSSQL Sharding Support](https://docs.microsoft.com/en-us/azure/architecture/patterns/sharding)

**Comment by v-ahibr** [comment]
The following Java EE APIs that were bundled with Java 6, 7, and 8 will no longer be on the class path by default in Java 9, but will still be available in the JDK.
 
```
java.activation
java.corba
java.transaction
java.xml.bind 
java.xml.ws
java.xml.ws.annotation
```

We will need to modify our code to no longer depend on these modules, or make the APIs available at runtime with this option:

`--add-modules java.se.ee`

**Comment by v-xiangs** [comment]
I looked at both [JDK 9](https://docs.oracle.com/javase/9/whatsnew/toc.htm#JSNEW-GUID-71A09701-7412-4499-A88D-53FA8BFBD3D0) Spec and [JDBC 4.3 Spec](http://download.java.net/java/jdk9/docs/api/java/sql/package-summary.html), nothing is very suspicious to me.

For JDK 9 security section, there were 2 things look suspicious in the beginning but we can remove our concerns after analyzing them:
* Disable SHA-1 Certificates: our AE windows certificate store has [X.509 certificate with SHA-1 based signatures](https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionCertificateStoreProvider.java#L139), but it is not called anywhere, we should remove it. So, this change in JDK 9 does not affect the driver.
* Create PKCS12 Keystores by Default: does not affect our driver, since we always specify the keystore name when creating a keystore

For JDBC 4.3,
* there is no breaking changes for the driver.
* Enhanced Connection and Sharding can be noticeable features.

**Comment by v-nisidh** [comment]
@v-xiangs : 
**For SHA-1 Certificates:** Disable SHA-1 in TLS Server certificate chains anchored by roots included by default in Oracle's JDK; **local** or **enterprise CAs** are **not affected**. 

Targeted Date: 2017-07-18

Ref: https://www.java.com/en/jre-jdk-cryptoroadmap.html

**Comment by v-xiangs** [comment]
@v-nisidh from my investigation, our driver does not uses SHA-1, I think we can ignore this change.

**Comment by v-afrafi** [comment]
Also check [Multi-Release JAR Files](http://openjdk.java.net/jeps/238) in Java9.

> Extend the JAR file format to allow multiple, Java-release-specific versions of class files to coexist in a single archive.

**Comment by nsidhaye** [comment]
Linking #506

**Comment by cheenamalhotra** [comment]
Closing the issue as we now support JDBC 4.3 APIs. Multi-release jars will be investigated with Java 11 support - tracked internally.
