### ISSUE TITLE
switch from 'SET FMTONLY' to alternative stored procedure

### ISSUE THREAD

**Issue by v-suhame** [Microsoft/mssql-jdbc#332]
`SET FMTONLY` is currently used in `SQLServerBulkCopy`, `SQLServerParameterMetaData` and `SQLServerPreparedStatement`, switch to alternative stored procedures [[listed in Note section]](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-fmtonly-transact-sql)  for SQL Server >=2012

**Comment by peterbae** [comment]
Out of those 3 places, SQLServerParameterMetadata is already using the new sproc for SQL Server >= 2012. As for the other remaining places that use SET FMTONLY, due to the difference in format between the resultsets returned from SET FMTONLY (which returns only the metadata with 0 rows) and the new sproc (they return a row for each column in the table, and the columns of the resultset represent each attribute of the column), it is difficult to replace the FMTONLY with the new sproc without doing one of the options below:

1. create an empty view/table that holds the same metadata as the target table, then select * from the empty table. This might have a detrimental effect on performance.
2. Change the behaviors of the caller methods (for instance, instead of expecting an empty resultset in SQLServerPreparedStatement, add an option to expect a resultset that has rows, and parse the results accordingly)

However, I believe that there might be an easier option other than employing one of those approaches, and I may come back to this issue when I find a better solution for this problem.

**Comment by peterbae** [comment]
Turns out FMTONLY is not fully replaced yet - the new stored procedures cannot be used to query for parameter metadata for encrypted columns, for example. Since we're going to rely on FMTONLY for as long as it's supported (and hopefully there will be a better replacement for it when it gets discontinued), we're going to close this issue.
