### ISSUE TITLE
Support setReadOnly()

### ISSUE THREAD

**Issue by mkurz** [Microsoft/mssql-jdbc#484]
Why [isn't `setReadOnly` supported](https://docs.microsoft.com/en-us/sql/connect/jdbc/reference/setreadonly-method-sqlserverconnection)? Are there any plans to do so? See line [3042](https://github.com/Microsoft/mssql-jdbc/issues/484#L3042):

https://github.com/Microsoft/mssql-jdbc/blob/19af32bb561685c681c364fbd4d2d02efdfd352b/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L3038-L3044

**Comment by ajlam** [comment]
Hi @mkurz, according to the JDBC spec, `setReadOnly` is not defined as mandatory. 

Would be happy to discuss the importance/use case of `setReadOnly` in your application/workload to try to understand what we can do to help you.

**Comment by peterbae** [comment]
I also looked into other JDBC driver implementations, and it seems MySQL is making use of the setReadOnly parameter, whereas Postgresql and jTBC drivers are recording the isReadOnly but not making use of it.

**Comment by mkurz** [comment]
@peterbae This is not correct, the PostgreSQL JDBC Driver **does** support the `setReadOnly` method:
https://github.com/pgjdbc/pgjdbc/blob/REL42.1.4/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L688-L704
What is jTBC?

@ajlam I was evaluating how to make sure that certain users of our web application can not insert/update/delete records in our database. I thought we could just switch on the read-only flag at the beginning of a http request (if the web app user only has read-only permissions) - and switch it off when the request ends (so it is back in the connection pool as it was). Advantage of this approach would be to just (re-)use one single connection pool (which initially hosts read-write connections).
An alternative solution for now would be to use a seperate connection pool for such users which contains just read-only connections. It seems that should be possible by setting up such read-only connections with `applicationIntent=ReadOnly` in the connection url/properties ([see docs](https://docs.microsoft.com/en-us/sql/connect/jdbc/jdbc-driver-support-for-high-availability-disaster-recovery#specifying-application-intent)). But also I am not sure if that is really working? See https://stackoverflow.com/questions/38356460/sql-server-application-intent-not-working-jdbc (I didn't try myself yet).
Also an alternative solution would be to use a seperate connection pool as well but with a read-only *user* on **database level** (instead of setting the intent connection property).
I know it is also possible to set a complete database to read only (`ALTER DATABASE...`) but that is clearly not an option for us as we have users who still want to write to the database.

As you can see we started looking into this as we were looking on how to make our database access more secure.

However we are also wondering if setting a connection (via `applicationIntent`) or certain queries within a connection (via `setReadOnly`) or using a db-level read-only user would result in better performance? Because maybe the database knows for sure there will not happen a write operation and therefore can optimize query plans, doesn't need to acquire locks, etc.
Are you aware of any positive effects on performance using read-only flag?
(I googled around a bit and found a page where they measured performance of a read-only database (`ALTER DATABASE ..`) was a few percent better than the same read-write database)

**Comment by cheenamalhotra** [comment]
Hi @mkurz, thanks for detailing out your requirement with us. 

It is true that you may find very minor performance improvements when you modify database to read-only mode by `ALTER DATABASE', but its not significant enough to be considered and also depends on your needs.

Looking at your requirement to secure database by restricting access to some users, the most optimum way to achieve this is by *Creating a database user with read-only privileges* on databases and connecting as read-only user every time restricted web-app users connect to your application. In this case, a separate connection pool can be maintained for read-only users such that it does not interfere with read-write connections.

Also, to clarify your doubts for `applicationIntent=ReadOnly`, this property can be used only on AlwaysOn AG and not legacy or read-only databases. It is used to enable read-only routing which creates a read-only replica of database and connects to it. Also, it may take longer than connecting to the primary database because read-only routing first connects to the primary and then looks for the best available readable secondary, which I think in your scenario, is not what you are looking for.

We have not considered providing support for 'setReadOnly' yet. It is said to boost some performance as database need not maintain transaction locks in this scenario, but you will need to make this property true for every connection read-only user is connecting to. On the contrary, significant performance improvement can be achieved by different means, e.g. using batches, optimized queries, creating indices on DB tables, etc.

**Comment by mkurz** [comment]
> We have not considered providing support for setReadOnly yet.

You mean providing support by the JDBC driver or within SQL Server itself? Is it possible to turn read-only on and off (back and forth) in SQL Server itself for an active connection right now? How can this be achieved - can you provide a SQL a snippet? If so, I think it would be probably not to hard to implement this in the JDBC driver - or am I wrong?

> ... but you will need to make this property true for every connection read-only user is connecting to.

This wouldn't be an issue for us as we have a well layered, modularized application source code where we could handle this globally (without the risk that a dev "forgets" to set/unset the read-only flag by automatically switching it depending on the role of the connected web app user).

> On the contrary, significant performance improvement can be achieved by different means, e.g. using batches, optimized queries, creating indices on DB tables, etc.

Yeah, for sure. I also thought there are probably many more obvious ways to improve performance. For us read-only isn't about performance improvements in the first place, but would be a nice side effect.

Anyway, I problably will go for the read-only database user with its dedicated connection pool for now.

However supporting `setReadOnly` would also be nice so people could choose from more options on how to desgin their databases and apps.

**Comment by cheenamalhotra** [comment]
I meant to say support for `setReadOnly` in JDBC driver, it isn't a hard implementation, we will start working on it as well (_Will keep this issue open to track implementation progress_).. We hadn't focused on it before as it is not defined as mandatory in JDBC specifications and we didn't receive any customer request for implementing this before.

I wanted to suggest a better solution to your use case, as an ideal solution seemed to be with database users with restricted access rights.

Thanks for bringing up the issue anyways, we will update you when we make the feature available.

**Comment by mkurz** [comment]
@cheenamalhotra thanks, great to hear this will be implemented! :+1: 

Also thanks to @ajlam and @peterbae for reaching out to me. :smile:

**Comment by cheenamalhotra** [comment]
`Is it possible to turn read-only on and off (back and forth) in SQL Server itself for an active connection right now? How can this be achieved - can you provide a SQL a snippet?`

Hi @mkurz We tried to find a solution for this - but unfortunately SQL Server doesn't support it by itself too. The link provided by you works for PostgresSQL since the database supports read only session properties. Unfortunately, for SQL Server there is no such thing, and that's the reason why no driver supports Read Only Connection to SQL Server. The only way to implement it is by driver intelligently detecting read-only property from connection and then behaving appropriately but that also means the driver gets to decide norms for 'read-only' connection.

We don't think that's an ideal solution too, and hence decided to not go ahead for implementation. Sorry for the delay since we were looking into lots of activities and checking all possibilities for providing support.

Let me know if you have any further questions.

**Comment by mkurz** [comment]
No further questions. Thanks for investing your time into this issue! Although it's a pity this is not possible we can live without that feature.

Thanks!

**Comment by cheenamalhotra** [comment]
Thanks @mkurz closing the issue !
