### ISSUE TITLE
[Feature] Keep unknown property when getting url from database metadata

### ISSUE THREAD

**Issue by hypnoce** [Microsoft/mssql-jdbc#486]
I'm writing features for jdbc distributed tracing. In particular, the ability to define the remote service name inside the connection string that will be parsed.
Unfortunately, unknown tokens are removed  from the final properties map.
```java
final Connection connection = DriverManager.getConnection("sqlserver://localhost;databaseName=master;foo=bar", "user", "password");
connection.getMetaData().getURL().contains("foo=bar"); //returns false
```
Indeed, in [SQLServerDriver.java#L576](https://github.com/Microsoft/mssql-jdbc/blob/19af32bb561685c681c364fbd4d2d02efdfd352b/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java#L576), null is returned for unknown tokens.

A quick fix would be to return the name instead of null but it might break some other logic in the code (even if the test passes locally on my machine)

What do you think of such feature. Does it make sense ?

Thanks
(PS: it works with other databases such as MySQL)

**Comment by cheenamalhotra** [comment]
Thanks @hypnoce, we are looking into the issue and will keep you posted!

**Comment by hypnoce** [comment]
Let me know if you need any help on this. I mean the fix is pretty simple from my point of view but I'm sure I'm missing some aspect

**Comment by cheenamalhotra** [comment]
Sure! We are currently investigating towards providing this feature, and impact this change would have on driver's existing behavior with applications. Also, if we find any better ways to handle your requirement we will let you know!

**Comment by hypnoce** [comment]
Deal !

**Comment by ajlam** [comment]
Hi @hypnoce, thanks for filing your issue. I understand that you'd like to be able to trace p6spy zipkin. Unfortunately, we have not heard of any other customers who want to pass in their own connection string properties, unknown to the JDBC Driver itself. 

Since this is not a typical ask from other customers, would you consider making the changes (equivalent to PR #489) to your own branch of the JDBC Driver and using that in your workload? I'm not sure how likely we are to merge your PR as there may be some security concerns with passing in unknown parameters through the connection string to the JDBC Driver.

**Comment by hypnoce** [comment]
Hi @ajlam, I understand your concern. Actually it's a new feature in zipkin that has been added very recently. I will see what I can do on my side. Thanks !

**Comment by ajlam** [comment]
Hi @hypnoce, thanks for your understanding. Please let us know if you have any other JDBC related issues. Happy to help 😄

**Comment by sehrope** [comment]
+1 to not supporting unknown properties. I like the explicit validation of connection properties as it provides validation that the properties are actually enabled.

Ignoring missing properties can cause problems when a user has an older version of a driver that doesn't support a newer property or, even worse, when they try to enable a property with a typo or incorrect name (ex: `ssl=true` instead of the actual property `encrypt=true`).

**Comment by hypnoce** [comment]
As I understood the code, typos in properties are  ignored and logged with fine level. So adding support for unknown properties (that still logs that they are unknown) won't make this situation worse nor better. The connection is not validated.

Nevertheless, I totally understand the security problem here. We could sanitize this part. Anyway, I think we may still have security issues with values as they don't seem sanitized (maybe I'm wrong here) unlike the keys that should match a set of predefined strings.

**Comment by ajlam** [comment]
Closing this issue. @hypnoce, please let us know if you have any additional questions.
