### ISSUE TITLE
DATETIME to TIMESTAMP

### ISSUE THREAD

**Issue by raghunathr85** [Microsoft/mssql-jdbc#511]
## Driver version or jar name
mssql-jdbc-6.2.1.jre8.jar

## SQL Server version
Microsoft SQL Server 2012 (SP3-GDR) (KB4019092) - 11.0.6251.0 (X64) 
	Jul  7 2017 07:14:24 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

## Client operating system
x86_64 GNU/Linux

## Java/JVM version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

## Table schema
CREATE TABLE [dbo].[Testtable]
(
  [ID] [uniqueidentifier]  NOT NULL,
  [recordDate] [datetime]  NULL
)
## Problem description
When extracting records from MS SQL through JDBC Connection, DATETIME converted into TIMESTAMP, trailing zeros are trimmed.

## Expected behavior and actual behavior
But, While conversion trailing zeros are getting stripped. Its good when we have all mmm.
Ex: 
2016-12-05 03:13:29.000 ==>2016-12-05 03:13:29.0
2016-12-05 03:13:29.897 ==> 2016-12-05 03:13:29.897

Is there is any way to preserve the zeros as well, as after extraction while doing data check its not matching with YYYY-MM-DD HH:mm:ss.SSS

## Repro code
Please share repro code with us, or tell us how to reproduce the issue.
Simple JDBC SELECT recordDate from table.

**Comment by cheenamalhotra** [comment]
Hi @raghunathr85, you can use [SimpleDateFormat](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html), to specify format in order to retain trailing zeroes and have safe comparison. 

Below code can be used to format Timestamp in desired format:
`new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(recordDate)`

Let us know if that resolves your issue.

**Comment by raghunathr85** [comment]
Is there is anyway, we can expect Timestamp in same format like SQL server.

I have given sample, like this we have multiple timestamp. so after JDBC explicitly we need to format.

Is there is any options to JDBC driver to preserve trailing zeros while we extract from SQL server?

**Comment by cheenamalhotra** [comment]
We could do that, if we were not restricted by JDBC `java.sql.Timestamp`'s behavior. As you can see [here](http://www.docjar.com/html/api/java/sql/Timestamp.java.html), at line no. 128 and 253, when Timestamp object is created from long Time, or String formatted as `"yyyy-MM-dd HH:mm:ss.SSS"`, nano-seconds are parsed to Integer and that is where it looses the trailing zeroes. 

Since the driver will create a new Timestamp object from either of the two methods, the resulted object will not contain trailing zeroes at any point. This is why no JDBC driver supports this as we can't can prevent trimming of zeroes from Timestamp object.

Suggested way is using SimpleDateFormat to compare 2 timestamps in desired format at client side. Let me know if you agree with me and I was able to explain you well.

**Comment by cheenamalhotra** [comment]
Hi @raghunathr85 did you get a chance to go through my comment above?

**Comment by v-afrafi** [comment]
Closing this issue. Please feel free to reopen it if not resolved. Thanks!
