### ISSUE TITLE
Provide a jar with bundled Azure dependencies

### ISSUE THREAD

**Issue by mparaz** [Microsoft/mssql-jdbc#550]
Could this project provide a jar file with the Azure jar dependencies bundled in? 
And then publish the jar as part of the official SQL Server JDBC driver distribution.

This is to make it easier for non-developers that use Java-based tools, such as the JetBrains DataGrip IDE.

**Comment by v-xiangs** [comment]
Hello @mparaz , thank you for creating an issue. 

Do you think if would be helpful if we create a section on our ReadMe page for non-developers regarding to how to download dependencies from Maven? 

I am not sure if it is legally allowed for Microsoft to publish a jar which is composed of other jars from maven. @David-Engel do you have any idea?

**Comment by mparaz** [comment]
Hi @v-xiangs - yes that's a good point about not being allowed to publish third-party code.

How about just making a build target with the bundled jar dependencies? Then the readme can mention what command they can use to build this jar. The instructions would need to be for non-developers (like, starting with "download Java").

**Comment by David-Engel** [comment]
@v-xiangs Legally, I suspect it would be fine as long as the 3rd party licenses allowed it.

Technically, I don't know if it's something we should do or not. I did a little reading on best practices for jar dependency bundling and it seems like we probably would not want to do that since our jar is not its own application. Feel free to disagree if you have done more research into it.

After reading, I'm not even sure we would want to provide a build target for it. It sounds like it might seem convenient but could also introduce package/library reference conflicts between other components of an application which consumes our jar.

**Comment by v-xiangs** [comment]
@David-Engel Thanks for the help. I agree with you that we shouldn't bundle dependencies. 

Do you think we should add a Wiki page (or ReadMe section ) on how to download dependencies from Maven with command `mvn dependency:copy-dependencies` ? It could be helpful for non-developers.

**Comment by David-Engel** [comment]
@v-xiangs Yes, I think a wiki page would be good. Thanks!

**Comment by v-xiangs** [comment]
Hello @mparaz , we created a [Wiki page](https://github.com/Microsoft/mssql-jdbc/wiki/Download-ADAL4J-And-AKV-Dependencies-with-Apache-Maven) for non-developers to download dependencies with Maven. Although it does not start with "download java", it's a very detailed instruction and explains step by step.
I am closing this issue for now, feel free to re-open it if you have more suggestions, thanks.
