### ISSUE TITLE
Wrapping sql statements in sp_executesql

### ISSUE THREAD

**Issue by agrothe** [Microsoft/mssql-jdbc#579]
## Driver version or jar name
6.2
## SQL Server version
2016 fully patched
## Client operating system
Win7
## Java/JVM version
1.7 via oracle

Have a JavaEE application that is being migrated from Oracle to SQL Server 2016. Uses Java 1.7, jboss 4.2.3.GA and hibernate 3.2.4.sp1.

The application uses the javax EntityManager for DB access and so queries look like this:

    List<ServiceProvider> providers = entityManager
            .createQuery("FROM ServiceProvider sp order by sp.id")
            .setMaxResults(spCount)
            .getResultList();

But a SQL Trace shows the query being wrapped in exec sp_executesql.

For example the above becomes exec sp_executesql N'SELECT TOP (50) ....'

If I trace a query coming from say an SSRS report, it is not wrapped in the sp_executesql.

Question: Will this or can this affect performance? My [question](https://stackoverflow.com/questions/47721098/mssql-sp-executesql-and-javax-persistence-entitymanager?noredirect=1#comment82414759_47721098) on SO pointed me at the driver being the cause of the sp_executesql stmt.

**Comment by agrothe** [comment]
Seems to be hibernate invoking the sp_executesql as I don't see it using jMeter. Closing.

**Comment by sql-sith** [comment]
@agrothe I know this issue is closed, but **sp_executesql** is your friend when used properly. It will look for a cached copy of an appropriate execution plan and compile one if needed. You can think of it as building anonymous stored procedures that are reusable whenever we discover that we are running the same query (after parameterization, etc.).
