### ISSUE TITLE
Writing performance of driver v6.5 is slower than sqljdbc41.jar (1.4 to 2.6 times slower)

### ISSUE THREAD

**Issue by jpoernomoatsafe** [Microsoft/mssql-jdbc#750]
## Driver version or jar name
mssql-jdbc-6.5.0.jre8-preview.jar

## SQL Server version
SQL Server 2014

## Client operating system
Windows 10

## Java/JVM version
Example: java version "1.8.0", IBM J9 VM

## Table schema
CREATE TABLE [jpoetest] ([mystring] varchar(200))
CREATE TABLE [jpoetest] ([mystring] varchar(200), [GEOM] geometry)

## Problem description
We noticed a significant performance drop when switching from `sqljdbc41.jar` to `mssql-jdbc-6.5.0.jre8-preview.jar`, both with and without geometry columns. 
Without geometry columns, the new driver is 1.4 times slower. (old: 1m40s, new: 2m21s)
With one geometry column, the new driver is 2.5 times slower. (old: 1m55s, new: 4m49s)

This is when writing using batched `PreparedStatement` (more of how we're using this driver under Repro Code)

## Expected behavior and actual behavior
the newer driver should have roughly the same performance as `sqljdbc41.jar`

## Repro code
```
int batchCount = 0;

Connection connection = getConnection();
PreparedStatement statement = connection.prepareStatement("INSERT INTO [jpoetest] ([mystring], [GEOM]) VALUES (?, ?)");
ParameterMetaData pmd = statement.getParameterMetaData();

List<MyTuple> entriesToAdd = getEntriesToAdd();

for (MyTuple entry : entriesToAdd) {
  for (int i = 1; pmd.getParameterCount(); ++i) {
    switch (pmd.getParameterType(i)) {
    case 12: // varchar type
      statement.setString(i, entry.getMyString());
      break;
    case -157: // geometry type
      statement.setBytes(i, entry.getGeomAsByteArray());
      break;
    }
  }
  statement.addBatch();
}

statement.ExecuteBatch();
connection.commit();
```

**Comment by rene-ye** [comment]
Hi @jpoernomoatsafe, can you provide the version of `sqljdbc41.jar` you're using.

**Comment by jpoernomoatsafe** [comment]
hello @rene-ye 
it was  `sqljdbc_4.1.5605.100_enu.tar.gz`, from https://msdn.microsoft.com/en-us/data/aa937725

**Comment by rene-ye** [comment]
Hi @jacobovazquez, I attempted to reproduce the performance degradation described above, and did not receive similar results. The most I saw was about 15%, and that compares a worst case run to a best case run. Do you have any more information on the following that could help me reproduce the issue:
1. The average size of the strings you're trying to add to the batch.
2. The number of entries.
3. All connection properties set (either set through string or set through connection object itself).

It's worth noting that 4.1 is a **very** old version of the driver, and the driver has changed a lot since then. I'd also like to take the time now to ask whether you're using the new Geometry setters with the new driver. I see here you're calculating the byte[] yourself, and just setting the Geometry type as a raw byte[]. The spatial datatype support introduced in 6.5.0 will not affect this use case.

**Comment by rene-ye** [comment]
@jpoernomoatsafe, sorry for the lapse in communication. After some further investigation, I've concluded that there is degradation in Statement.getParameterMetaData(). This is caused by recent changes to cache statement metadata. If your application is calling this function frequently, turning on caching by adding "disableStatementPooling=false" and "statementPoolingCacheSize=10" to the connection properties should actually improve performance. There have been some suggestions on further improving this feature, and the team will look into minimizing impact when the caching is off.

**Comment by jpoernomoatsafe** [comment]
@rene-ye 

those connection properties have really improved performance for both our SQL Azure and SQL Server writers. thanks for those!
