### ISSUE TITLE
Unable to insert selected column data  using writeToServer

### ISSUE THREAD

**Issue by sumit88** [Microsoft/mssql-jdbc#813]
## Driver version
RTW-V6.4.0.jre7

## Client Operating System
CentOS 7

## JAVA/JVM version
java version "1.8.0_171"

**Comment by peterbae** [comment]
Hi @sumit88, thanks for contacting us. I see that you opened PR https://github.com/Microsoft/mssql-jdbc/pull/812/files to reflect this change.

I've read over the PR and it seems like we already provide this functionality. The name of the column is supposed to be provided through the SQLServerBulkBatchInsertRecord.addColumnMetadata() method, instead being provided through the writeToServer method. Giving an option to provide this through writeToServer would be superfluous and conflict with the existing Bulk Copy design.

Please let me know if you have any other questions - otherwise, we'll go ahead and close this issue and the PR.

**Comment by sumit88** [comment]
Hi Peter,


you are absolutely right. However if you'll look at the spark azure driver
provided by Microsoft itself, you'll see that it uses writeToServer method
to bulkcopy data through spark data frames. That's the reason why I want to
have this polymorphic form. The azure spark driver program method is
bulkCopy
If it does gets included in the driver then only I'll be in a position to
add my commit to the spark azure driver to use this polymorphic form
instead to insert records with few columns when its provided

Regards
Sumit

**Comment by peterbae** [comment]
Hi @sumit88, could you share some more details for me to help you better? Specifically:

- Could you share your Java code that uses our JDBC driver (I assume the Java application is trying to use Bulk Copy API?)
- Could you let me know exactly which spark azure driver you're referring to, and the API page that shows their writeToServer method?

Thanks,

**Comment by peterbae** [comment]
Hi @sumit88, I hope you're doing well. Did you have an update on this issue?

**Comment by peterbae** [comment]
Closing the issue due to inactivity. Please feel free to re-open this issue if you need further assistance.
