### ISSUE TITLE
getFunctionColumns() is missing SPECIFIC_NAME column

### ISSUE THREAD

**Issue by Impakt** [Microsoft/mssql-jdbc#849]
according to the [Javadocs](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getFunctionColumns(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)) the `getFunctionColumns` method is supposed to return a column called `SPECIFIC_NAME`, but the driver doesn't include it, see [here](https://github.com/Microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java#L664)

**Comment by cheenamalhotra** [comment]
HI @Impakt 

We will investigate the missing column and get back to you soon!

**Comment by ulvii** [comment]
Hi @Impakt ,

I looked into the issue and agree that the returned result set does not contain `SPECIFIC_NAME` column when it is supposed to.  

Please note that SQL Server function names **are unique within their schema** and `FUNCTION_NAME` is always the same as `SPECIFIC_NAME`.  For this reason, `sp_sproc_columns` (SQL Server procedure that gets invoked when you call `getFunctionColumns`) does not return `SPECIFIC_NAME` column in the result set. Would using `FUNCTION_NAME` instead of `SPECIFIC_NAME` resolve the issue for you?

I also investigated if the driver can duplicate `FUNCTION_NAME` column and append it to the result set as `SPECIFIC_NAME`. To achieve this, the driver would have to create a temporary table to join the output of `sp_sproc_columns` with the new `SPECIFIC_NAME` column, which obviously would result in a performance/memory overhead to get redundant information. 

Please let us know what you think.

**Comment by Impakt** [comment]
We changed our code to not assume that the 'column' would be there. It sounds like a lot of work to add the column to the result set so maybe just leave it out

**Comment by ulvii** [comment]
Hi @Impakt ,

Glad you could find a workaround. Please let us know if you have any other questions.

**Comment by onacit** [comment]
getFunctions() also misses the column.

**Comment by onacit** [comment]
The `SPECIFIC_NAME` is important that it could(should) be uses the uniqueness of the result.
