### ISSUE TITLE
Always Encrypted doesn't work with pivot

### ISSUE THREAD

**Issue by h3adache** [Microsoft/mssql-jdbc#874]
## Driver version
6.0.7507.100

## SQL Server version
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) 

## Client Operating System
Debian GNU/Linux 7.11 (wheezy)

## JAVA/JVM version
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

## Problem description
1. Expected behaviour:
   select statements with PIVOT should still allow decryption of encrypted fields

2. Actual behaviour:
   fields that are in the pivot are not decrypted

I can create a simple example if needed but the gist is imagine the simple pivot example on msql doc
```
SELECT 'AverageCost' AS Cost_Sorted_By_Production_Days,   
[0], [1], [2], [3], [4]  
FROM  
(SELECT DaysToManufacture, StandardCost   
    FROM Production.Product) AS SourceTable  
PIVOT  
(  
MIN(StandardCost)  
FOR DaysToManufacture IN ([0], [1], [2], [3], [4])  
) AS PivotTable;  
```
Imagine the standardcost field to be always encrypted
I change StandardCost to be an AE field and AVG to MIN.
Otherwise it's the same code.
What I expect is that the StandardCost would return back unencrypted if I have the proper settings (`sqlServerDataSource.setColumnEncryptionSetting("Enabled"); // needed for Always Encrypted`) and the proper CMK.
But the code will run without errors but without decrypting StandardCost.

If I remove the pivot and just return StandardCost, it DOES show up decrypted correctly.

I haven't tested newer jdbc drivers because I can't find any relevant changes that might affect this (correct me if I'm wrong)

**Comment by peterbae** [comment]
Hi @h3adache, thanks for contacting us. In this case, the query with AE table would not work because of the MIN(StandardCost). While the driver is responsible for decrypting the encrypted data sent back to the client, the MIN function is handled by the SQL Server (before any data is sent back to the driver), and the SQL Server will not allow you to perform MIN function on an encrypted data. Basically, with this query, the first thing the driver receives from the SQL Server would be the error message, and it didn't get a chance to decrypt any data.

If you wanted to use this PIVOT query with AE, it'll probably have to be a two-step process involving your own stored procedure to allow the driver to decrypt the data first, then providing the decrypted data to your stored procedure.

Please let me know if you have any other questions.

**Comment by h3adache** [comment]
Ok thanks! That makes sense @peterbae. 
Would the secure enclave in 2019 help with this?
For now the 2 step process, I'm not sure how a stored proc would work here.
I have to get back the results to the client side first for the AE to work if I understand you, 'before any data is sent back to the driver' being the issue.
So how do I get the results of a stored proc back to the client and then back to a pivot query? I can just pivot in the client code at that point I would imagine?

**Comment by peterbae** [comment]
We haven't tested with secure enclave, but it seems like it allows you to encrypt/decrypt the data locally on the server side, which would help with this scenario (but this is more of a SQL Server subject rather than JDBC at this point, since the server will be doing the decryption now).

There's multiple ways to achieve the pivot query, but my first impression was that the client would select the encrypted columns from the table, then either 1) call a stored procedure (that you wrote) that takes in the values that the JDBC driver decrypted (and uses that to somehow achieve the desired pivot query), or 2) insert the decrypted data into a temp table, then simply execute the same pivot query we have above with the temp table. But I suppose you wouldn't necessarily need to use a stored procedure since you could just pivot in the client code like you suggested as well.

**Comment by h3adache** [comment]
Great thanks @peterbae!

**Comment by peterbae** [comment]
Closing issue as this is more of a server side implementation.
