### ISSUE TITLE
Please publish Maven artifacts for the x86 and x64 auth DLLs

### ISSUE THREAD

**Issue by bturner** [microsoft/mssql-jdbc#907]
Thanks for publishing Maven artifacts for the SQL Server JDBC driver!

In Atlassian Bitbucket Server, we bundle the JDBC driver jar, and we also bundle the x86 and x64 versions of `sqljdbc_auth.dll` to facilitate using integrated authentication on Windows. Prior to Microsoft publishing their own jars for the JDBC driver we would manually publish them to our internal Maven repository, along with the DLLs. Now we can use the Microsoft-published jar for the JDBC driver, but we still need to manually publish the auth DLLs.

We use classifiers to differentiate the x86 and x64 DLLs, so our dependencies look like this:
```xml
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc_auth</artifactId>
    <classifier>x64</classifier>
    <type>dll</type>
</dependency>
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc_auth</artifactId>
    <classifier>x86</classifier>
    <type>dll</type>
</dependency>
```

Is there any chance Microsoft could start publishing the auth DLLs (and maybe the `sqljdbc_xa` DLLs for completeness, though we don't need those)? I assume the DLLs change from time to time, and that would imply it's important to use the DLL version that matches the JDBC driver version. (That's why we package the DLLs; that way we're certain the DLL and driver match.)

Thanks for your consideration!

**Comment by David-Engel** [comment]
Thanks for the suggestion. That's actually a good idea. They do not change frequently, although there are occasional bug fixes. I'll have to see if there are any restrictions on the legal side to publishing them on Maven since they are not included under the MIT license that this repo is under. We will discuss it with the team.

**Comment by Fuerte1** [comment]
Hello, we would also like to see sqljdbc_auth.dll in Maven, both x86 and x64.

**Comment by ulvii** [comment]
Hi everyone,
We are working on publishing the DLLs on Maven, which will automatically rename the DLLs to also contain version and bitness information. For example, the definitions below would generate mssql-jdbc_auth-8.1.1.x64-preview.dll and mssql-jdbc_auth-8.1.1.x86-preview.dll respectively.
```
<dependency>
  <groupId>com.microsoft.sqlserver</groupId>
  <artifactId>mssql-jdbc_auth</artifactId>
  <version>8.1.1.x64-preview</version>
  <type>dll</type>
</dependency>
```
```
<dependency>
  <groupId>com.microsoft.sqlserver</groupId>
  <artifactId>mssql-jdbc_auth</artifactId>
  <version>8.1.1.x86-preview</version>
  <type>dll</type>
</dependency>
```
Because DLL names contain bitness information, this means we also need to change the driver code that refers to the DLL name [here](https://github.com/microsoft/mssql-jdbc/blob/8d2c52ee049ca126ca9bcbdec4b8a0beb3096626/src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java#L51) and [here](https://github.com/microsoft/mssql-jdbc/blob/8d2c52ee049ca126ca9bcbdec4b8a0beb3096626/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L6499). Unfortunately, there does not seem to be a portable and robust way of detecting JVM bitness (to decide DLL name) from inside the driver. We managed to workaround this issue [when loading the DLL](https://github.com/microsoft/mssql-jdbc/blob/8d2c52ee049ca126ca9bcbdec4b8a0beb3096626/src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java#L51) by first trying to load 64-bit DLL, if it fails assume JVM is 32-bit. 
However, the [second reference in SQLServerConnectionSecurityManager](https://github.com/microsoft/mssql-jdbc/blob/8d2c52ee049ca126ca9bcbdec4b8a0beb3096626/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L6499) needs the static DLL name to [check if the current thread is allowed to dynamically load the DLL](https://github.com/microsoft/mssql-jdbc/blob/8d2c52ee049ca126ca9bcbdec4b8a0beb3096626/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L6530).
At this point, the only solution that comes to my mind is to handle each JVM vendor differently to detect its bitness, but I first wanted to check if there are any suggestions.
@bturner, you mentioned you already uploaded the DLLs to a private repository, I assume you also modified the driver code to load them or you rename the DLLs after Maven download? It would be helpful if you shared details of your setup.

**Comment by Fuerte1** [comment]
Hello, how we detect bitness:
```
    static int getBits() {
        if (bits == 0) {
            String dataModel = System.getProperty("sun.arch.data.model");
            bits = Integer.parseInt(dataModel); // 32 or 64
        }
        return bits;
    }
```
But we handle sqljdbc_auth.dll loading differently, we copy the correct bitness version to a folder and set 
-Djava.library.path=folder
to that folder, so that the normal jdbc driver loads it. So I think that the jdbc driver does not need to check the bitness, it would be enough that both 64- and 32-bit dll versions are available in Maven, we can then handle the bitness at deploy time.
Of course, if the target is to have jdbc driver and dll embedded to application and loaded dynamically, then it gets more complicated in jdbc driver, but might be easier in some cases. But in our case, we don't even want to have jdbc driver in our application itself, but it is used in web server database connection pool.

**Comment by jborgland** [comment]
That only works with an Oracle JVM unfortunately.

But I agree, it could probably be left to the applications to select the
dll.

Den tis 5 nov. 2019 kl 09:32 skrev Fuerte1 <notifications@github.com>:

**Comment by ulvii** [comment]
When the DLLs are uploaded to Maven, they are automatically renamed to contain the version. For example, if you upload 8.1.1 version of sqljdbc_auth.dll, it will become sqljdbc_auth-8.1.1.dll. We also want to make that the driver version always matches the DLL version. This already means the driver code needs to be modified to load the library. Maven also does not let you to upload two artifacts (32-bit, 64-bit) with the same version. To workaround this issue, we decided to add bitness to the version, the same way we handle jre8, jre11, jre13 jars on Maven. As a result, the DLL names become mssql-jdbc_auth-8.1.1.x64-preview.dll and mssql-jdbc_auth-8.1.1.x86-preview.dll (sqljdbc to mssql-jdbc for consistency with the jar name).

That being said, my testing shows that `System.getProperty("os.arch");` returns `x86` for 32-bit, `amd64` for 64-bit JVMs, regardless of the OS bitness (at least on Windows). For now I will continue with this plan, let me know if I am missing something.

**Comment by Fuerte1** [comment]
Sounds good! Because the DLL names are different, we can then put them into same folder, which simplifies deployment.

**Comment by ulvii** [comment]
Hi everyone,
The [x64](https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc_auth/8.1.1.x64-preview/dll) and [x86](https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc_auth/8.1.1.x86-preview/dll) DLLs are uploaded to Maven together with .pdb files. Below is how you'd add them as a dependency:
```
<dependency>
  <groupId>com.microsoft.sqlserver</groupId>
  <artifactId>mssql-jdbc_auth</artifactId>
  <version>8.1.1.x64-preview</version>
  <type>dll</type>
</dependency>
```
```
<dependency>
  <groupId>com.microsoft.sqlserver</groupId>
  <artifactId>mssql-jdbc_auth</artifactId>
  <version>8.1.1.x86-preview</version>
  <type>dll</type>
</dependency>
```
Closing the issue, please let me know if you have any questions.

**Comment by bturner** [comment]
Massive thanks, @ulvii! This will make it much simpler for us to consume newer driver versions directly, rather than needing to re-host parts of them.
