### ISSUE TITLE
[BUG] the index 1 is out of range

### ISSUE THREAD

**Issue by leefine** [Microsoft/mssql-jdbc#964]
## Problem description

 When i upgrade the driver from 7.0.0.jre8 to  7.2.0.jre8, the mybatis runs with sql server giving the error: 
the index 1 is out of range

**Comment by christophs78** [comment]
We have the same issue:

UPDATE TDOKUMENT SET REIHE=REIHE-1 WHERE RID= ? AND REIHE <= ? AND REIHE > ? AND DID <> ?
Der Index "1" liegt außerhalb des gültigen Bereichs. SQLState: S1093 ErrorCode: 0
UPDATE TRAUM SET REIHE=REIHE-1 WHERE PARENT= ? AND REIHE <= ? AND REIHE > ? AND RID <> ?
Der Index "1" liegt außerhalb des gültigen Bereichs. SQLState: S1093 ErrorCode: 0

**Comment by rene-ye** [comment]
[Hotfix 7.2.1](https://github.com/Microsoft/mssql-jdbc/releases/tag/v7.2.1) was recently released and should address this issue. #952 contains majority of the discussion. Please try the hotfix version and see if it fixes the issues.

**Comment by leefine** [comment]
yes,V 7.2.1.jre8 is ok,this issue can be closed.

**Comment by JDBC-0** [comment]
This bug can have mutliplt causes ... we learned the hard way (even with jTDS driver), that this error message is also set if the access rights to certain database objects were not sufficient enough. (E.g. called procedure accessed another database object that was located in another database ... this error vanished after we set additional access rights for the call in this iother database too.)

So, this error should be bettr (if possible) so that the driver sets a different error message. E.g. "Acces not allowed for call of <proceudr>....", instead of "Index '1' out of range".
